/*
 * Copyright (C) 2014 Institute for Bioinformatics and Systems Biology, University Giessen, Germany
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package de.cebitec.readxplorer.transcriptionanalyses;


import de.cebitec.readxplorer.databackend.ResultTrackAnalysis;
import de.cebitec.readxplorer.databackend.dataObjects.PersistentFeature;
import de.cebitec.readxplorer.exporter.tables.TableExportFileChooser;
import de.cebitec.readxplorer.transcriptionanalyses.dataStructures.RPKMvalue;
import de.cebitec.readxplorer.ui.analysis.ResultTablePanel;
import de.cebitec.readxplorer.ui.tablevisualization.TableUtils;
import de.cebitec.readxplorer.ui.tablevisualization.tablefilter.TableRightClickFilter;
import de.cebitec.readxplorer.ui.visualisation.reference.ReferenceFeatureTopComp;
import de.cebitec.readxplorer.utils.UneditableTableModel;
import java.util.HashMap;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.openide.util.Exceptions;


/**
 * Panel showing a result of an analysis filtering for features with a
 * min and max certain readcount.
 * <p>
 * @author -Rolf Hilker-
 */
public class ResultPanelRPKM extends ResultTablePanel {

    private static final long serialVersionUID = 1L;

    public static final String RETURNED_FEATURES = "Total number of returned features";
    public static final String FEATURES_TOTAL = "Total number of reference features";

    private RPKMAnalysisResult rpkmCalcResult;
    private final HashMap<String, Integer> filterStatisticsMap;
    private PersistentFeature feature;
    private final boolean statistics = false;
    private final TableRightClickFilter<UneditableTableModel> tableFilter;
    private ReferenceFeatureTopComp refComp;


    /**
     * Panel showing a result of an analysis filtering for features with a min
     * and max certain readcount.
     */
    public ResultPanelRPKM() {
        initComponents();
        final int posIdx = 0;
        final int trackIdx = 2;
        final int chromIdx = 3;
        tableFilter = new TableRightClickFilter<>( UneditableTableModel.class, posIdx, trackIdx );
        this.rpkmTable.getTableHeader().addMouseListener( tableFilter );
        this.filterStatisticsMap = new HashMap<>();
        this.filterStatisticsMap.put( RETURNED_FEATURES, 0 );
        this.refComp = ReferenceFeatureTopComp.findInstance();

        DefaultListSelectionModel model = (DefaultListSelectionModel) this.rpkmTable.getSelectionModel();
        model.addListSelectionListener( new ListSelectionListener() {

            @Override
            public void valueChanged( ListSelectionEvent e ) {
                TableUtils.showPosition( rpkmTable, posIdx, chromIdx, getBoundsInfoManager() );
                refComp.showTableFeature( rpkmTable, 0 );
            }


        } );
    }


    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parametersLabel = new javax.swing.JLabel();
        histogramButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rpkmTable = new javax.swing.JTable();
        exportButton = new javax.swing.JButton();
        statisticsButton = new javax.swing.JButton();

        parametersLabel.setText(org.openide.util.NbBundle.getMessage(ResultPanelRPKM.class, "ResultPanelRPKM.parametersLabel.text_1")); // NOI18N

        histogramButton.setText(org.openide.util.NbBundle.getMessage(ResultPanelRPKM.class, "ResultPanelRPKM.histogramButton.text_1")); // NOI18N
        histogramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histogramButtonActionPerformed(evt);
            }
        });

        rpkmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Feature", "Feature Type", "Track", "Chromosome", "Strand", "Start", "Stop", "Length", "RPKM", "Read Count"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Double.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(rpkmTable);
        if (rpkmTable.getColumnModel().getColumnCount() > 0) {
            rpkmTable.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(ResultPanelRPKM.class, "ResultPanelRPKM.rpkmTable.columnModel.title0_1")); // NOI18N
            rpkmTable.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(ResultPanelRPKM.class, "ResultPanelRPKM.rpkmTable.columnModel.title5_1")); // NOI18N
            rpkmTable.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(ResultPanelRPKM.class, "ResultPanelRPKM.rpkmTable.columnModel.title8_1")); // NOI18N
            rpkmTable.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(ResultPanelRPKM.class, "ResultPanelRPKM.rpkmTable.columnModel.title9")); // NOI18N
            rpkmTable.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(ResultPanelRPKM.class, "ResultPanelRPKM.rpkmTable.columnModel.title4_1")); // NOI18N
            rpkmTable.getColumnModel().getColumn(5).setHeaderValue(org.openide.util.NbBundle.getMessage(ResultPanelRPKM.class, "ResultPanelRPKM.rpkmTable.columnModel.title1_1")); // NOI18N
            rpkmTable.getColumnModel().getColumn(6).setHeaderValue(org.openide.util.NbBundle.getMessage(ResultPanelRPKM.class, "ResultPanelRPKM.rpkmTable.columnModel.title2_1")); // NOI18N
            rpkmTable.getColumnModel().getColumn(7).setHeaderValue(org.openide.util.NbBundle.getMessage(ResultPanelRPKM.class, "ResultPanelRPKM.rpkmTable.columnModel.title7_1")); // NOI18N
            rpkmTable.getColumnModel().getColumn(8).setHeaderValue(org.openide.util.NbBundle.getMessage(ResultPanelRPKM.class, "ResultPanelRPKM.rpkmTable.columnModel.title3_1")); // NOI18N
            rpkmTable.getColumnModel().getColumn(9).setHeaderValue(org.openide.util.NbBundle.getMessage(ResultPanelRPKM.class, "ResultPanelRPKM.rpkmTable.columnModel.title6_1")); // NOI18N
        }

        exportButton.setText(org.openide.util.NbBundle.getMessage(ResultPanelRPKM.class, "ResultPanelRPKM.exportButton.text_1")); // NOI18N
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        statisticsButton.setText(org.openide.util.NbBundle.getMessage(ResultPanelRPKM.class, "ResultPanelRPKM.statisticsButton.text")); // NOI18N
        statisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(parametersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 568, Short.MAX_VALUE)
                .addComponent(statisticsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(histogramButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportButton))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(histogramButton)
                    .addComponent(parametersLabel)
                    .addComponent(exportButton)
                    .addComponent(statisticsButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void histogramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histogramButtonActionPerformed
        if( !statistics ) {
            try {
                ResultHistogramRPKM hist = new ResultHistogramRPKM( this.rpkmCalcResult );
            }
            catch( Exception ex ) {
                Exceptions.printStackTrace( ex );
            }
        }
    }//GEN-LAST:event_histogramButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        TableExportFileChooser fileChooser = new TableExportFileChooser( TableExportFileChooser.getTableFileExtensions(), rpkmCalcResult );
    }//GEN-LAST:event_exportButtonActionPerformed

    private void statisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsButtonActionPerformed
        JOptionPane.showMessageDialog( this, new RpkmStatsPanel( filterStatisticsMap ), "RPKM and Read Count Statistics", JOptionPane.INFORMATION_MESSAGE );
    }//GEN-LAST:event_statisticsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exportButton;
    private javax.swing.JButton histogramButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel parametersLabel;
    private javax.swing.JTable rpkmTable;
    private javax.swing.JButton statisticsButton;
    // End of variables declaration//GEN-END:variables


    /**
     * Adds a list of features with read count and RPKM values to this panel.
     * <p>
     * @param newResult the new result to add
     */
    @Override
    public void addResult( ResultTrackAnalysis newResult ) {

        tableFilter.setTrackMap( newResult.getTrackMap() );

        if( newResult instanceof RPKMAnalysisResult ) {
            RPKMAnalysisResult rpkmCalcResultNew = (RPKMAnalysisResult) newResult;
//            boolean moreThanOneChrom = rpkmCalcResultNew.getChromosomeMap().size() > 1;
            final int nbColumns = 10;

            if( this.rpkmCalcResult == null ) {
                this.rpkmCalcResult = rpkmCalcResultNew;
                this.filterStatisticsMap.put( FEATURES_TOTAL, rpkmCalcResultNew.getNoGenomeFeatures() );
            }
            else {
                this.rpkmCalcResult.getResults().addAll( rpkmCalcResultNew.getResults() );
            }
            DefaultTableModel model = (DefaultTableModel) this.rpkmTable.getModel();

            PersistentFeature feat;
            for( RPKMvalue rpkm : rpkmCalcResult.getResults() ) {
                feat = rpkm.getFeature();
                Object[] rowData = new Object[nbColumns];
                int i = 0;
                rowData[i++] = feat;
                rowData[i++] = feat.getType();
                rowData[i++] = this.rpkmCalcResult.getTrackEntry( rpkm.getTrackId(), false );
                rowData[i++] = rpkmCalcResultNew.getChromosomeMap().get( feat.getChromId() );
                rowData[i++] = feat.isFwdStrandString();
                rowData[i++] = feat.getStartOnStrand();
                rowData[i++] = feat.getStopOnStrand();
                rowData[i++] = feat.getLength();
                rowData[i++] = rpkm.getRPKM();
                rowData[i++] = rpkm.getReadCount();

                model.addRow( rowData );
            }

            TableRowSorter<TableModel> sorter = new TableRowSorter<>();
            this.rpkmTable.setRowSorter( sorter );
            sorter.setModel( model );

            ParameterSetRPKM rpkmParams = (ParameterSetRPKM) rpkmCalcResult.getParameters();
            this.parametersLabel.setText( org.openide.util.NbBundle.getMessage( ResultPanelRPKM.class,
                                                                                "ResultPanelRPKM.parametersLabel.text", rpkmParams.getMinReadCount(), rpkmParams.getMaxReadCount() ) );

            filterStatisticsMap.put( RETURNED_FEATURES, filterStatisticsMap.get( RETURNED_FEATURES ) + rpkmCalcResultNew.getResults().size() );
            rpkmCalcResult.setStatsMap( filterStatisticsMap );
        }
    }


    /**
     * @return the number of features filtered during the associated analysis
     */
    @Override
    public int getDataSize() {
        return this.rpkmCalcResult.getResults().size();
    }


}
