/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cebitec.readXplorer.transcriptomeAnalyses.featureTableExport;

import static de.cebitec.readXplorer.transcriptomeAnalyses.featureTableExport.SequinTableSettingsWizardPanel.SEQUIN_EXPORT_FEATURE_NAME;
import java.util.prefs.Preferences;
import javax.swing.JPanel;
import org.openide.util.NbPreferences;

public final class SequinTableSettingsVisualPanel extends JPanel {

    private final String wizardName;

    /**
     * Creates new form SequinTableSettingsVisualPanel
     */
    public SequinTableSettingsVisualPanel(String wizardName) {
        this.wizardName = wizardName;
        initComponents();
        updateFields();
    }

    @Override
    public String getName() {
        return "Sequin Table Export";
    }

    /**
     * Getter for the taped feature.
     *
     * @return featurename
     */
    public String getFeatureName() {
        return this.featureTF.getText();
    }

    private void updateFields() {
        Preferences pref = NbPreferences.forModule(Object.class);
        this.featureTF.setText(pref.get(wizardName + SEQUIN_EXPORT_FEATURE_NAME, ""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        featureTF = new javax.swing.JTextField();
        dataSelectionContainer = new javax.swing.JPanel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(SequinTableSettingsVisualPanel.class, "SequinTableSettingsVisualPanel.jLabel1.text")); // NOI18N

        featureTF.setText(org.openide.util.NbBundle.getMessage(SequinTableSettingsVisualPanel.class, "SequinTableSettingsVisualPanel.featureTF.text")); // NOI18N

        javax.swing.GroupLayout dataSelectionContainerLayout = new javax.swing.GroupLayout(dataSelectionContainer);
        dataSelectionContainer.setLayout(dataSelectionContainerLayout);
        dataSelectionContainerLayout.setHorizontalGroup(
            dataSelectionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        dataSelectionContainerLayout.setVerticalGroup(
            dataSelectionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataSelectionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(featureTF)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(featureTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dataSelectionContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dataSelectionContainer;
    private javax.swing.JTextField featureTF;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
