/*
 * CustomFileChooser.java
 *
 * Created on 18.05.2010, 13:51:23
 */

package de.cebitec.vamp.differentialExpression;

import java.io.File;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author kstaderm
 */
public class CustomFileSaver extends javax.swing.JFrame {

    private diffExpVisualPanel3 controll;
    private FileFilter filter = new FileFilter() {

        public boolean accept(File pathname) {
            if(pathname.getName().endsWith(".png") || pathname.isDirectory()){
                return true;
            } else {
                return false;
            }
        }

        @Override
        public String getDescription() {
            return "*.png";
        }
    };
    /** Creates new form CustomFileChooser */
    public CustomFileSaver() {
        initComponents();
    }

    public CustomFileSaver(diffExpVisualPanel3 controll) {
        this.controll = controll;
        initComponents();
        jFileChooser1.setFileFilter(filter);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        if(evt.getActionCommand().equals("ApproveSelection")){
            this.setVisible(false);
            controll.setPath(jFileChooser1.getSelectedFile().getPath());
            this.dispose();
        }
        if(evt.getActionCommand().equals("CancelSelection")){
            this.dispose();
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
