/*
 * ResultPanelFilteredGenes.java
 *
 * Created on 27.01.2012, 14:31:15
 */
package de.cebitec.vamp.transcriptionAnalyses;

import de.cebitec.vamp.transcriptionAnalyses.dataStructures.FilteredGene;
import de.cebitec.vamp.databackend.dataObjects.PersistantAnnotation;
import de.cebitec.vamp.exporter.excel.ExcelExportFileChooser;
import de.cebitec.vamp.util.SequenceUtils;
import de.cebitec.vamp.view.dataVisualisation.BoundsInfoManager;
import java.util.List;
import javax.swing.DefaultListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 * @author -Rolf Hilker-
 */
public class ResultPanelFilteredGenes extends javax.swing.JPanel {

    private BoundsInfoManager bim;
    private List<FilteredGene> filteredGenes;
    
    /** Creates new form ResultPanelFilteredGenes */
    public ResultPanelFilteredGenes() {
        initComponents();
        
        DefaultListSelectionModel model = (DefaultListSelectionModel) this.filteredGenesTable.getSelectionModel();
        model.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                showFilteredGenePosition();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expressedGenesPane = new javax.swing.JScrollPane();
        filteredGenesTable = new javax.swing.JTable();
        exportButton = new javax.swing.JButton();

        filteredGenesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Annotation", "Strand", "Total Read Count"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        expressedGenesPane.setViewportView(filteredGenesTable);
        filteredGenesTable.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(ResultPanelFilteredGenes.class, "ResultPanelFilteredGenes.filteredGenesTable.columnModel.title0")); // NOI18N
        filteredGenesTable.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(ResultPanelFilteredGenes.class, "ExpressedGenesResultPanel.expressedGenesTable.columnModel.title2_1")); // NOI18N
        filteredGenesTable.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(ResultPanelFilteredGenes.class, "ExpressedGenesResultPanel.expressedGenesTable.columnModel.title1")); // NOI18N

        exportButton.setText(org.openide.util.NbBundle.getMessage(ResultPanelFilteredGenes.class, "ResultPanelFilteredGenes.exportButton.text")); // NOI18N
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addComponent(exportButton))
            .addComponent(expressedGenesPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(expressedGenesPane, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        FilteredGenesColumns filteredGenesData = new FilteredGenesColumns(this.filteredGenes);
        ExcelExportFileChooser fileChooser = new ExcelExportFileChooser("xls", filteredGenesData, "Filtered Genes Table"); 
    }//GEN-LAST:event_exportButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exportButton;
    private javax.swing.JScrollPane expressedGenesPane;
    private javax.swing.JTable filteredGenesTable;
    // End of variables declaration//GEN-END:variables

    private void showFilteredGenePosition() {
        DefaultListSelectionModel model = (DefaultListSelectionModel) this.filteredGenesTable.getSelectionModel();
        int selectedView = model.getLeadSelectionIndex();
        int selectedModel = this.filteredGenesTable.convertRowIndexToModel(selectedView);
        PersistantAnnotation annotation = (PersistantAnnotation) this.filteredGenesTable.getModel().getValueAt(selectedModel, 0);
        int pos = annotation.getStrand() == SequenceUtils.STRAND_FWD ? annotation.getStart() : annotation.getStop();

        bim.navigatorBarUpdated(pos);
    }

    public void setBoundsInfoManager(BoundsInfoManager boundsInformationManager) {
        this.bim = boundsInformationManager;
    }

    public void addFilteredGenes(List<FilteredGene> filteredGenes) {
        final int nbColumns = 3;
        this.filteredGenes = filteredGenes;
        DefaultTableModel model = (DefaultTableModel) this.filteredGenesTable.getModel();        

        for (FilteredGene filteredGene : this.filteredGenes) {
            
            Object[] rowData = new Object[nbColumns];
            rowData[0] = filteredGene.getFilteredAnnotation();
            rowData[1] = filteredGene.getFilteredAnnotation().getStrand() == SequenceUtils.STRAND_FWD ? "Fwd" : "Rev";
            rowData[2] = filteredGene.getReadCount();

            model.addRow(rowData);
        }

        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>();
        this.filteredGenesTable.setRowSorter(sorter);
        sorter.setModel(model);
    }
    
    public int getResultSize() {
        return this.filteredGenes.size();
    }
}
