package de.cebitec.vamp.ui.visualisation.reference;

import de.cebitec.vamp.view.dataVisualisation.referenceViewer.ReferenceViewer;

/**
 *
 * @author ddoppmeier
 */
public class CodonSelector extends javax.swing.JPanel {

    private final static long serialVersionUID = 24966;

    private ReferenceViewer viewer;

    /** Creates new form CodonSelector */
    public CodonSelector() {
        initComponents();
    }

    public void setGenomeViewer(ReferenceViewer viewer){
        this.viewer = viewer;
        checkBoxes();
    }

    /**
     * Used to check for boxes that are checked when a new viewer was selected.
     *
     */
    private void checkBoxes(){
        atgCheckbox.setSelected(viewer.getSequenceBar().isATGCodonShown());
        gtgCheckbox.setSelected(viewer.getSequenceBar().isGTGCodonShown());
        ttgCheckbox.setSelected(viewer.getSequenceBar().isTTGCodonShown());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atgCheckbox = new javax.swing.JCheckBox();
        ttgCheckbox = new javax.swing.JCheckBox();
        gtgCheckbox = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Highlighted codons"));

        atgCheckbox.setText("ATG");
        atgCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atgCheckboxActionPerformed(evt);
            }
        });

        ttgCheckbox.setText("TTG");
        ttgCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttgCheckboxActionPerformed(evt);
            }
        });

        gtgCheckbox.setText("GTG");
        gtgCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtgCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(atgCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ttgCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gtgCheckbox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atgCheckbox)
                    .addComponent(ttgCheckbox)
                    .addComponent(gtgCheckbox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atgCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atgCheckboxActionPerformed
        viewer.getSequenceBar().showATGCodon(atgCheckbox.isSelected());
}//GEN-LAST:event_atgCheckboxActionPerformed

    private void ttgCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttgCheckboxActionPerformed
        viewer.getSequenceBar().showTTGCodon(ttgCheckbox.isSelected());
}//GEN-LAST:event_ttgCheckboxActionPerformed

    private void gtgCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtgCheckboxActionPerformed
        viewer.getSequenceBar().showGTGCodon(gtgCheckbox.isSelected());
}//GEN-LAST:event_gtgCheckboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox atgCheckbox;
    private javax.swing.JCheckBox gtgCheckbox;
    private javax.swing.JCheckBox ttgCheckbox;
    // End of variables declaration//GEN-END:variables

}
