package de.cebitec.vamp.ui.dataAdministration;

import de.cebitec.vamp.parser.ReferenceJob;
import de.cebitec.vamp.parser.TrackJobs;
import java.util.Iterator;
import java.util.List;
import org.openide.util.NbBundle;

/**
 *
 * @author ddoppmeier
 */
public class OverviewCard extends javax.swing.JPanel {
    
    private static final long serialVersionUID = 1L;

    /** Creates new form OverviewCard */
    public OverviewCard() {
        initComponents();
    }

    public void showGenereateOverview(List<ReferenceJob> scheduledRefGenJobs, List<TrackJobs> scheduledTrackJobs) {
        jTextArea1.setText("");

        if(!scheduledRefGenJobs.isEmpty()){
            jTextArea1.append("References:\n");
            for(Iterator<ReferenceJob> it = scheduledRefGenJobs.iterator(); it.hasNext() ;){
                ReferenceJob r = it.next();
                jTextArea1.append(r.getName()+"\n");
                jTextArea1.append("\t"+r.getDescription()+"\n");
            }
            jTextArea1.append("\n");
        }

        if(!scheduledTrackJobs.isEmpty()){
            jTextArea1.append("Tracks:\n");
            for(Iterator<TrackJobs> it = scheduledTrackJobs.iterator(); it.hasNext(); ){
                TrackJobs r = it.next();
                jTextArea1.append(r.getDescription()+"\n");
            }
            jTextArea1.append("\n");
        }
    }

    @Override
    public String getName() {
        return NbBundle.getMessage(this.getClass(), "CTL_OverviewCard.name");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
