package de.cebitec.vamp.ui.dataAdministration;

import de.cebitec.vamp.parser.ReferenceJob;
import de.cebitec.vamp.parser.TrackJobs;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.List;
import org.openide.util.NbBundle;

/**
 *
 * @author ddoppmeier
 */
public class SelectionCard extends javax.swing.JPanel {
    
    private static final long serialVersionUID = 1L;

    public static final String PROP_HAS_CHECKED_JOBS = "hasCheckedJobs";

    /** Creates new form DataAdminPanel */
    public SelectionCard() {
        initComponents();
        refGenView.addPropertyChangeListener(PROP_HAS_CHECKED_JOBS, getHasCheckedJobsListener());
        mappingView.addPropertyChangeListener(PROP_HAS_CHECKED_JOBS, getHasCheckedJobsListener());
        mappingView.addPropertyChangeListener(TrackView.PROP_DESELECT, new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                refGenView.deselectRefGen((ReferenceJob) evt.getNewValue());
            }
        });
    }

    public void setSelectableJobs(List<ReferenceJob> refJobs, List<TrackJobs> trackJobs){
        refGenView.setReferenceJobs(refJobs);
        mappingView.setTrackJobs(trackJobs);
    }

    public List<ReferenceJob> getRef2DelJobs(){
        return refGenView.getJobs2del();
    }

    public List<TrackJobs> getTrack2DelJobs(){
        return mappingView.getJobs2Del();
    }

    private PropertyChangeListener getHasCheckedJobsListener(){
        return new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                firePropertyChange(evt.getPropertyName(), evt.getOldValue(), evt.getNewValue());
            }
        };
    }

    @Override
    public String getName() {
        return NbBundle.getMessage(SelectionCard.class, "CTL_SelectionCard.name");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        refGenView = new de.cebitec.vamp.ui.dataAdministration.ReferenceView();
        mappingView = new de.cebitec.vamp.ui.dataAdministration.TrackView();

        jTabbedPane1.addTab("References", refGenView);
        jTabbedPane1.addTab("Tracks", mappingView);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private de.cebitec.vamp.ui.dataAdministration.TrackView mappingView;
    private de.cebitec.vamp.ui.dataAdministration.ReferenceView refGenView;
    // End of variables declaration//GEN-END:variables

}
