package de.cebitec.vamp.view.dialogMenus;

import de.cebitec.vamp.util.Observer;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javafx.scene.paint.Color;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.control.ProgressIndicator;
import javafx.scene.layout.StackPane;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import org.openide.windows.WindowManager;

/**
 *
 * @author Kai
 */
public class Loading extends javax.swing.JPanel implements Observer {

    private JFrame mainFrame = (JFrame) WindowManager.getDefault().getMainWindow();
    private JDialog dia;

    /**
     * Creates new form Loading
     */
    public Loading() {
        Platform.setImplicitExit(false);
        mainFrame.setEnabled(false);
        initComponents();
        this.setOpaque(false);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                initAndShowGUI();
            }
        });
        initDialog();
    }

    private void initDialog() {
        dia = new JDialog(mainFrame);
        Dimension dim = new Dimension(250, 250);
        dia.setSize(dim);
        dia.setPreferredSize(dim);
        dia.add(this);
        int x = ((mainFrame.getWidth() - 250) / 2) + mainFrame.getX();
        int y = ((mainFrame.getHeight() - 250) / 2) + mainFrame.getY();
        dia.setLocation(x, y);
        dia.setUndecorated(true);
        dia.requestFocus();
        dia.getRootPane().setOpaque(false);
        dia.getContentPane().setBackground(new java.awt.Color(0, 0, 0, 0));
        dia.setBackground(new java.awt.Color(0, 0, 0, 0));
        dia.setVisible(true);
    }

    private void initAndShowGUI() {
        final JFXPanel fxPanel = new JFXPanel();
        this.setLayout(new BorderLayout());
        this.add(fxPanel, BorderLayout.CENTER);

        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                initFX(fxPanel);
            }
        });
    }

    private static void initFX(JFXPanel fxPanel) {
        Scene scene = createScene();
        fxPanel.setScene(scene);
    }

    private static Scene createScene() {
        StackPane root = new StackPane();
        Scene scene = new Scene(root, 250, 250);
        scene.setFill(Color.TRANSPARENT);
        ProgressIndicator pi = new ProgressIndicator(-1.0);
        root.getChildren().add(pi);
        return (scene);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Object args) {
        finished();
    }

    public void finished() {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                dia.dispose();
                mainFrame.setEnabled(true);
                mainFrame.requestFocus();
            }
        });
    }
}
