package vamp.view.dataAdministration;

import java.util.Iterator;
import java.util.List;
import vamp.importer.ReferenceJob;
import vamp.importer.RunJob;
import vamp.importer.TrackJob;

/**
 *
 * @author ddoppmeier
 */
public class OverviewCard extends javax.swing.JPanel {

    private View view;

    /** Creates new form OverviewCard */
    public OverviewCard() {
        initComponents();
    }

    public void setDataAdminView(View view){
        this.view = view;
    }

    public void showGenereateOverview(List<ReferenceJob> scheduledRefGenJobs, List<RunJob> scheduledRunJobs, List<TrackJob> scheduledTrackJobs) {
        jTextArea1.setText("");

        if(!scheduledRefGenJobs.isEmpty()){
            jTextArea1.append("References:\n");
            for(Iterator<ReferenceJob> it = scheduledRefGenJobs.iterator(); it.hasNext() ;){
                ReferenceJob r = it.next();
                jTextArea1.append(r.getName()+"\n");
                jTextArea1.append("\t"+r.getDescription()+"\n");
            }
            jTextArea1.append("\n");
        }

        if(!scheduledRunJobs.isEmpty()){
            jTextArea1.append("Runs:\n");
            for(Iterator<RunJob> it = scheduledRunJobs.iterator(); it.hasNext(); ){
                RunJob r = it.next();
                jTextArea1.append(r.getDescription()+"\n");
            }
            jTextArea1.append("\n");
        }

        if(!scheduledTrackJobs.isEmpty()){
            jTextArea1.append("Tracks:\n");
            for(Iterator<TrackJob> it = scheduledTrackJobs.iterator(); it.hasNext(); ){
                TrackJob r = it.next();
                jTextArea1.append(r.getDescription()+"\n");
            }
            jTextArea1.append("\n");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        view.startDeletion();
        view.showProgressCard();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        view.showSelectionCard();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
