package de.cebitec.readXplorer.transcriptomeAnalyses.main;

import java.awt.BorderLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.text.StyledDocument;

/**
 *
 * @author jritter
 */
public class MotifSearchPanel extends javax.swing.JPanel {

    public static final String CURRENT_DIR = "currentDirectory";

    /**
     * Creates new form MotifSearchPanel
     */
    public MotifSearchPanel() {
        initComponents();
        additionalInits();
    }

    /**
     * Some additional settings on components like setting borders.
     */
    private void additionalInits() {
        promotorsPanel.setBorder(BorderFactory.createTitledBorder("Promotor region in Fasta format"));
        promotorsInFastaTextPane.setEditable(true);
        promotorsInFastaTextPane.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 12));
        minus35RegionPanel.setBorder(BorderFactory.createTitledBorder("Region of intrest (-35)"));
        minus10RegionPanel.setBorder(BorderFactory.createTitledBorder("Region of intrest (-10)"));
        regionOfIntrestMinusThirtyviveTP.setEditable(false);
        regionOfIntrestMinusThirtyviveTP.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 12));
        regionOfIntrestMinusTenTP.setEditable(false);
        regionOfIntrestMinusTenTP.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 12));
        this.infoPanel.setBorder(BorderFactory.createTitledBorder("Info panel"));

        this.minus10LogoPanel.setBorder(BorderFactory.createTitledBorder("-10 Motif"));
        this.minus10LogoPanel.setLayout(new BorderLayout());
        this.minus35LogoPanel.setBorder(BorderFactory.createTitledBorder("-35 Motif"));
        this.minus35LogoPanel.setLayout(new BorderLayout());
    }

    public void setMinSpacer1LengthToLabel(Integer length) {
        this.minSpacer1Label.setText(length.toString());
    }

    public void setMinSpacer2LengthToLabel(Integer length) {
        this.minSpacer2Label.setText(length.toString());
    }

    public void setMinus10MotifWidth(Integer width) {
        this.motifWidthLabel10.setText(width.toString());
    }

    public void setMinus35MotifWidth(Integer width) {
        this.motifWidthLabel35.setText(width.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        promotorsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        promotorsInFastaTextPane = new javax.swing.JTextPane();
        minus35LogoPanel = new javax.swing.JPanel();
        minus10LogoPanel = new javax.swing.JPanel();
        minus35RegionPanel = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        regionOfIntrestMinusThirtyviveTP = new javax.swing.JTextPane();
        minus10RegionPanel = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        regionOfIntrestMinusTenTP = new javax.swing.JTextPane();
        infoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        motifWidthLabel35 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        minSpacer2Label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        motifWidthLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        minSpacer1Label = new javax.swing.JLabel();

        jScrollPane1.setViewportView(promotorsInFastaTextPane);

        javax.swing.GroupLayout promotorsPanelLayout = new javax.swing.GroupLayout(promotorsPanel);
        promotorsPanel.setLayout(promotorsPanelLayout);
        promotorsPanelLayout.setHorizontalGroup(
            promotorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(promotorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE))
        );
        promotorsPanelLayout.setVerticalGroup(
            promotorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(promotorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout minus35LogoPanelLayout = new javax.swing.GroupLayout(minus35LogoPanel);
        minus35LogoPanel.setLayout(minus35LogoPanelLayout);
        minus35LogoPanelLayout.setHorizontalGroup(
            minus35LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        minus35LogoPanelLayout.setVerticalGroup(
            minus35LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout minus10LogoPanelLayout = new javax.swing.GroupLayout(minus10LogoPanel);
        minus10LogoPanel.setLayout(minus10LogoPanelLayout);
        minus10LogoPanelLayout.setHorizontalGroup(
            minus10LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        minus10LogoPanelLayout.setVerticalGroup(
            minus10LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane9.setViewportView(regionOfIntrestMinusThirtyviveTP);

        javax.swing.GroupLayout minus35RegionPanelLayout = new javax.swing.GroupLayout(minus35RegionPanel);
        minus35RegionPanel.setLayout(minus35RegionPanelLayout);
        minus35RegionPanelLayout.setHorizontalGroup(
            minus35RegionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        minus35RegionPanelLayout.setVerticalGroup(
            minus35RegionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minus35RegionPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane10.setViewportView(regionOfIntrestMinusTenTP);

        javax.swing.GroupLayout minus10RegionPanelLayout = new javax.swing.GroupLayout(minus10RegionPanel);
        minus10RegionPanel.setLayout(minus10RegionPanelLayout);
        minus10RegionPanelLayout.setHorizontalGroup(
            minus10RegionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        minus10RegionPanelLayout.setVerticalGroup(
            minus10RegionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(MotifSearchPanel.class, "MotifSearchPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(motifWidthLabel35, org.openide.util.NbBundle.getMessage(MotifSearchPanel.class, "MotifSearchPanel.motifWidthLabel35.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(MotifSearchPanel.class, "MotifSearchPanel.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(minSpacer2Label, org.openide.util.NbBundle.getMessage(MotifSearchPanel.class, "MotifSearchPanel.minSpacer2Label.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(MotifSearchPanel.class, "MotifSearchPanel.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(motifWidthLabel10, org.openide.util.NbBundle.getMessage(MotifSearchPanel.class, "MotifSearchPanel.motifWidthLabel10.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(MotifSearchPanel.class, "MotifSearchPanel.jLabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(minSpacer1Label, org.openide.util.NbBundle.getMessage(MotifSearchPanel.class, "MotifSearchPanel.minSpacer1Label.text")); // NOI18N

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(motifWidthLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(minSpacer2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(motifWidthLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(minSpacer1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(motifWidthLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(minSpacer2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(motifWidthLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minSpacer1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(promotorsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(minus35RegionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(minus10RegionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(minus35LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(minus10LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(promotorsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minus35RegionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minus10RegionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(minus35LogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minus10LogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel minSpacer1Label;
    private javax.swing.JLabel minSpacer2Label;
    private javax.swing.JPanel minus10LogoPanel;
    private javax.swing.JPanel minus10RegionPanel;
    private javax.swing.JPanel minus35LogoPanel;
    private javax.swing.JPanel minus35RegionPanel;
    private javax.swing.JLabel motifWidthLabel10;
    private javax.swing.JLabel motifWidthLabel35;
    private javax.swing.JTextPane promotorsInFastaTextPane;
    private javax.swing.JPanel promotorsPanel;
    private javax.swing.JTextPane regionOfIntrestMinusTenTP;
    private javax.swing.JTextPane regionOfIntrestMinusThirtyviveTP;
    // End of variables declaration//GEN-END:variables

    public void setStyledDocumentToRegionOfIntrestMinusTen(StyledDocument doc) {

        this.regionOfIntrestMinusTenTP.setStyledDocument(doc);
    }

    public void setStyledDocumentToRegionOfIntrestMinus35(StyledDocument doc) {
        this.regionOfIntrestMinusThirtyviveTP.setStyledDocument(doc);
    }

    public void setStyledDocToPromotorsFastaPane(StyledDocument doc) {
        this.promotorsInFastaTextPane.setStyledDocument(doc);
    }

    public void setMinus10LogoToPanel(JLabel logo) {
        this.minus10LogoPanel.add(logo, BorderLayout.CENTER);
    }

    public void setMinus35LogoToPanel(JLabel logo) {
        this.minus35LogoPanel.add(logo, BorderLayout.CENTER);
    }
}
