/*
 * NewTrackDialogPanel.java
 *
 * Created on 13.01.2011, 15:18:28
 */
package de.cebitec.readXplorer.ui.importer;

import de.cebitec.readXplorer.parser.mappings.JokToBamDirectParser;
import de.cebitec.readXplorer.parser.mappings.MappingParserI;
import de.cebitec.readXplorer.parser.mappings.SamBamDirectParser;
import de.cebitec.readXplorer.api.objects.NewJobDialogI;
import de.cebitec.readXplorer.parser.ReferenceJob;
import de.cebitec.readXplorer.parser.common.ParserI;
import de.cebitec.readXplorer.util.fileChooser.ReadXplorerFileChooser;
import de.cebitec.readXplorer.view.dialogMenus.ImportTrackBasePanel;
import java.awt.Component;
import java.io.File;
import java.util.List;
import javax.swing.*;
import javax.swing.text.NumberFormatter;
import org.openide.util.NbBundle;

/**
 * Panel displaying the options for importing new tracks into ReadXplorer.
 *
 * @author jwinneba, rhilker
 */
public class NewTrackDialogPanel extends ImportTrackBasePanel implements NewJobDialogI {

    private static final long serialVersionUID = 774275254;
    private ReferenceJob[] refGenJobs;
    
    private final JokToBamDirectParser jokToBamDirectParser;
    private final SamBamDirectParser samBamDirectParser;
    private MappingParserI[] parsers;
    
    private int stepSize = 0;
    private static final int maxVal = 1000000000;
    private static final int minVal = 10000;
    private static final int step = 1000;
    private static final int defaultVal = 300000;

    /** 
     * Panel displaying the options for importing new tracks into ReadXplorer. 
     */
    public NewTrackDialogPanel() {
        this.refGenJobs = this.getReferenceJobs();
        this.jokToBamDirectParser = new JokToBamDirectParser();
        this.samBamDirectParser = new SamBamDirectParser();
        this.parsers = new MappingParserI[] { this.samBamDirectParser, jokToBamDirectParser };
        // choose the default parser. first entry is shown in combobox by default
        this.setCurrentParser(this.parsers[0]);
        this.initComponents();
        this.setStepwiseField(false);
        this.setStepSizeSpinner();
        this.multiTrackScrollPane.setVisible(false);
        this.multiTrackListLabel.setVisible(false);

    }

    /**
     * @return true, if all required info for this track job dialog is set, 
     * false otherwise.
     */
    @Override
    public boolean isRequiredInfoSet() {
        if (getMappingFiles().isEmpty() || refGenBox.getSelectedItem() == null || nameField.getText().isEmpty()) {
            return false;
        } else {
            return true;
        }
    }

    /**
     * @return The name of this track.
     */
    @Override
    public String getTrackName() {
        return nameField.getText();
    }

    /**
     * @return The reference genome associated with this track job.
     */
    @Override
    public ReferenceJob getReferenceJob() {
        return (ReferenceJob) refGenBox.getSelectedItem();
    }

    public boolean isFileSorted() {
        return fileSorted.isSelected();
    }

    public Integer getStepSize() {
        stepSize = (Integer) stepSizeSpinner.getValue();

        return stepSize;
    }

    /**
     * Creates the jspinner for setting the step size of the import.
     */
    private void setStepSizeSpinner() {
        stepSizeSpinner.setModel(new SpinnerNumberModel(defaultVal, minVal, maxVal, step));
        JFormattedTextField txt = ((JSpinner.NumberEditor) stepSizeSpinner.getEditor()).getTextField();
        ((NumberFormatter) txt.getFormatter()).setAllowsInvalid(false);

    }

    private void setStepwiseField(boolean setFields) {
        stepSizeLabel.setVisible(setFields);
        stepSizeSpinner.setVisible(setFields);
        fileSorted.setVisible(setFields);
    }

    /**
     * @param jobs list of reference jobs which shall be imported now and thus
     *      have to be available for the import of new tracks too.
     */
    public void setReferenceJobs(List<ReferenceJob> jobs) {
        refGenBox.setModel(new DefaultComboBoxModel<>(this.getReferenceJobs(jobs)));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mappingTypeLabel = new javax.swing.JLabel();
        mappingFileLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        refGenLabel = new javax.swing.JLabel();
        refGenBox = new javax.swing.JComboBox<>(refGenJobs);
        mappingFileField = new javax.swing.JTextField();
        chooseButton = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        mappingTypeCombo = new javax.swing.JComboBox<>(parsers);
        stepSizeLabel = new javax.swing.JLabel();
        stepSizeSpinner = new javax.swing.JSpinner();
        fileSorted = new javax.swing.JCheckBox();
        alreadyImportedBox = new javax.swing.JCheckBox();
        multipleImportCheckBox = new javax.swing.JCheckBox();
        multiTrackScrollPane = new javax.swing.JScrollPane();
        multiTrackList = new javax.swing.JList<>();
        multiTrackListLabel = new javax.swing.JLabel();

        mappingTypeLabel.setText(org.openide.util.NbBundle.getMessage(NewTrackDialogPanel.class, "NewTrackDialogPanel.mappingTypeLabel.text")); // NOI18N

        mappingFileLabel.setText(org.openide.util.NbBundle.getMessage(NewTrackDialogPanel.class, "NewTrackDialogPanel.mappingFileLabel.text")); // NOI18N

        nameLabel.setText(org.openide.util.NbBundle.getMessage(NewTrackDialogPanel.class, "NewTrackDialogPanel.nameLabel.text")); // NOI18N

        refGenLabel.setText(org.openide.util.NbBundle.getMessage(NewTrackDialogPanel.class, "NewTrackDialogPanel.refGenLabel.text")); // NOI18N

        mappingFileField.setEditable(false);
        mappingFileField.setText(org.openide.util.NbBundle.getMessage(NewTrackDialogPanel.class, "NewTrackDialogPanel.mappingFileField.text")); // NOI18N

        chooseButton.setText(org.openide.util.NbBundle.getMessage(NewTrackDialogPanel.class, "NewTrackDialogPanel.chooseButton.text")); // NOI18N
        chooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseButtonActionPerformed(evt);
            }
        });

        mappingTypeCombo.setRenderer(new DefaultListCellRenderer(){
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus){
                if(value instanceof ParserI){
                    return super.getListCellRendererComponent(list, ((ParserI) value).getName(), index, isSelected, cellHasFocus);
                } else {
                    return super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                }
            }
        });
        mappingTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mappingTypeComboActionPerformed(evt);
            }
        });

        stepSizeLabel.setText(org.openide.util.NbBundle.getMessage(NewTrackDialogPanel.class, "NewTrackDialogPanel.stepSizeLabel.text")); // NOI18N

        fileSorted.setSelected(true);
        fileSorted.setText(org.openide.util.NbBundle.getMessage(NewTrackDialogPanel.class, "NewTrackDialogPanel.fileSorted.text")); // NOI18N

        alreadyImportedBox.setText(org.openide.util.NbBundle.getMessage(NewTrackDialogPanel.class, "NewTrackDialogPanel.alreadyImportedBox.text")); // NOI18N
        alreadyImportedBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alreadyImportedBoxActionPerformed(evt);
            }
        });

        multipleImportCheckBox.setText(org.openide.util.NbBundle.getMessage(NewTrackDialogPanel.class, "NewTrackDialogPanel.multipleImportCheckBox.text")); // NOI18N
        multipleImportCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleImportCheckBoxActionPerformed(evt);
            }
        });

        multiTrackScrollPane.setViewportView(multiTrackList);

        multiTrackListLabel.setText(org.openide.util.NbBundle.getMessage(NewTrackDialogPanel.class, "NewTrackDialogPanel.multiTrackListLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(refGenLabel)
                    .addComponent(stepSizeLabel)
                    .addComponent(nameLabel)
                    .addComponent(mappingFileLabel)
                    .addComponent(mappingTypeLabel)
                    .addComponent(multiTrackListLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alreadyImportedBox)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stepSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fileSorted))
                            .addComponent(multipleImportCheckBox))
                        .addGap(35, 35, 35))
                    .addComponent(refGenBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mappingFileField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseButton))
                    .addComponent(multiTrackScrollPane)
                    .addComponent(nameField)
                    .addComponent(mappingTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refGenBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refGenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mappingTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mappingTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mappingFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseButton)
                    .addComponent(mappingFileLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stepSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileSorted)
                    .addComponent(stepSizeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alreadyImportedBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multipleImportCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(multiTrackListLabel)
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addComponent(multiTrackScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseButtonActionPerformed
        this.getMappingFiles().clear();
        ReadXplorerFileChooser fc = new ReadXplorerFileChooser(getCurrentParser().getFileExtensions(), getCurrentParser().getInputFileDescription()) {
            private static final long serialVersionUID = 1L;

            @Override
            public void save(String fileLocation) {
                throw new UnsupportedOperationException("Not supported.");
            }

            @Override
            public void open(String fileLocation) {

                // file chosen
                if (useMultipleImport()) {
                    File[] files = this.getSelectedFiles();
                    getMappingFiles().clear();

                    for (int i = 0; i < files.length; ++i) {
                        addFile(files[i], mappingFileField);
                        nameField.setText(files[i].getName());
                        if (!(getCurrentParser() instanceof JokToBamDirectParser)) {
                            checkSeqDictonary(files[i]);
                        }
                    }

                    mappingFileField.setText(getMappingFiles().size() + " tracks to import");
                    DefaultListModel<String> model = new DefaultListModel<>();
                    fillMultipleImportTable(model, getMappingFiles(), "Mapping file list:");
                    multiTrackList.setModel(model);
                    nameField.setText("Note: each track gets its file name");
                } else {
                    File file = this.getSelectedFile();
                    addFile(file, mappingFileField);
                    nameField.setText(file.getName());
                    if (!(getCurrentParser() instanceof JokToBamDirectParser)) {
                        checkSeqDictonary(file);
                    }
                }
            }
        };
        
        fc.setDirectoryProperty("NewTrack.Filepath");
        fc.setMultiSelectionEnabled(this.useMultipleImport());
        fc.openFileChooser(ReadXplorerFileChooser.OPEN_DIALOG);
}//GEN-LAST:event_chooseButtonActionPerformed
    
    private void mappingTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mappingTypeComboActionPerformed
        MappingParserI newparser = (MappingParserI) this.mappingTypeCombo.getSelectedItem();
        if (this.getCurrentParser() != newparser) {
            this.setCurrentParser(newparser);
            this.multiTrackList.setModel(new DefaultListModel<String>());
            this.getMappingFiles().clear();
            this.mappingFileField.setText("");
            this.nameField.setText("");
            this.setStepwiseField(false);
            if (newparser instanceof SamBamDirectParser) {
                this.alreadyImportedBox.setEnabled(true);
            } else {
                this.alreadyImportedBox.setEnabled(false);
                this.alreadyImportedBox.setSelected(false);
                this.setIsAlreadyImported(false);
            }
        }
    }//GEN-LAST:event_mappingTypeComboActionPerformed

    private void multipleImportCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleImportCheckBoxActionPerformed
        this.updateGuiForMultipleFiles(multipleImportCheckBox, multiTrackScrollPane, multiTrackList, multiTrackListLabel, mappingFileField);
        if (this.useMultipleImport()) {
            nameField.setEnabled(false);
            nameField.setText(NbBundle.getMessage(NewTrackDialogPanel.class, "MultipleImportTrackNameMsg"));
        } else {
            this.nameField.setEnabled(true);
            this.nameField.setText("");
        }
    }//GEN-LAST:event_multipleImportCheckBoxActionPerformed

    private void alreadyImportedBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alreadyImportedBoxActionPerformed
        this.setIsAlreadyImported(this.alreadyImportedBox.isSelected());
    }//GEN-LAST:event_alreadyImportedBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alreadyImportedBox;
    private javax.swing.JButton chooseButton;
    private javax.swing.JCheckBox fileSorted;
    private javax.swing.JTextField mappingFileField;
    private javax.swing.JLabel mappingFileLabel;
    private javax.swing.JComboBox<MappingParserI> mappingTypeCombo;
    private javax.swing.JLabel mappingTypeLabel;
    private javax.swing.JList<String> multiTrackList;
    private javax.swing.JLabel multiTrackListLabel;
    private javax.swing.JScrollPane multiTrackScrollPane;
    private javax.swing.JCheckBox multipleImportCheckBox;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox<ReferenceJob> refGenBox;
    private javax.swing.JLabel refGenLabel;
    private javax.swing.JLabel stepSizeLabel;
    private javax.swing.JSpinner stepSizeSpinner;
    // End of variables declaration//GEN-END:variables

}
