/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RemoveTrackListPanel.java
 *
 * Created on 29.03.2011, 22:33:32
 */

package de.cebitec.vamp.thumbnail;

import de.cebitec.vamp.databackend.dataObjects.PersistantFeature;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import javax.swing.JList;

/**
 *
 * @author Denis
 */
public class RemoveFeatureListPanel extends javax.swing.JPanel {
    private List<PersistantFeature> selectedFeatures;
    
    /** Creates new form RemoveTrackListPanel */
    public RemoveFeatureListPanel() {
        initComponents();
    }

    private PersistantFeature[] fillList(){
        return (PersistantFeature[]) selectedFeatures.toArray(new PersistantFeature[0]);
    }

    RemoveFeatureListPanel(List<PersistantFeature> features) {
        selectedFeatures = features;
        initComponents();        
    }

    public Object[] getSelectedValues(){
       return jList1.getSelectedValues();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList(this.fillList());
        jLabel1 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jList1);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(RemoveFeatureListPanel.class, "RemoveFeatureListPanel.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
