/*
 * ReadSearchSetup.java
 *
 * Created on 25.02.2011, 11:34:33
 */

package de.cebitec.vamp.tools.readSearch;

import de.cebitec.vamp.databackend.connector.TrackConnector;
import de.cebitec.vamp.objects.Read;
import java.util.List;
import javax.swing.SwingWorker;
import org.openide.util.RequestProcessor;
import org.openide.util.RequestProcessor.Task;
import org.openide.util.TaskListener;

/**
 *
 * @author jwinneba
 */
public class ReadSearchSetup extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private TrackConnector trackCon;
    private List<Read> reads;

    /** Creates new form ReadSearchSetup */
    public ReadSearchSetup() {
        initComponents();
    }

    private void findReads(){
        RequestProcessor rp = new RequestProcessor("ReadSearch Thread", 2);
        final Task searchTask = rp.post(new ReadSearcher());
        searchTask.addTaskListener(new TaskListener() {

            @Override
            public void taskFinished(org.openide.util.Task task) {
                firePropertyChange("readSearchFinished", null, reads);
                searchTask.removeTaskListener(this);
            }
        });
    }

    private class ReadSearcher extends SwingWorker<List<Read>, Object>{

        @Override
        protected List<Read> doInBackground() throws Exception {
            reads = trackCon.findReads(readNameField.getText());
            return reads;
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        readNameField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText(org.openide.util.NbBundle.getMessage(ReadSearchSetup.class, "ReadSearchSetup.jTextArea1.text")); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ReadSearchSetup.class, "ReadSearchSetup.jLabel1.text")); // NOI18N

        searchButton.setText(org.openide.util.NbBundle.getMessage(ReadSearchSetup.class, "ReadSearchSetup.searchButton.text")); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(readNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(readNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        findReads();
}//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField readNameField;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables

    public List<Read> getReads() {
        return reads;
    }

    public void setTrackCon(TrackConnector trackCon) {
        this.trackCon = trackCon;
    }

}
