package de.cebitec.vamp.ui.converter;

import de.cebitec.vamp.parser.output.ConverterI;
import de.cebitec.vamp.parser.output.JokToBamConverter;
import de.cebitec.vamp.util.GeneralUtils;
import de.cebitec.vamp.util.fileChooser.VampFileChooser;
import javax.swing.JOptionPane;
import org.openide.util.NbBundle;

/**
 *
 * @author Rolf Hilker <rhilker at cebitec.uni-bielefeld.de>
 */
public class ConverterSetupCard extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    private String filePath;
    private String fileExtension; //TODO: add file extension to converter
    private ConverterI[] availableParsers = new ConverterI[]{new JokToBamConverter()};
    private ConverterI currentConverter;
    private String referenceName;
    private int referenceLength;
    private boolean canConvert;
    
    /**
     * Creates new form ConverterSetupCard
     */
    public ConverterSetupCard() {
        initComponents();
        this.initAdditionalData();
    }
    
    private void initAdditionalData() {
        this.converterComboBox.setSelectedIndex(0);
        this.currentConverter = availableParsers[0];
        this.referenceLength = -1;
        this.selectConverter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        converterComboBox = new javax.swing.JComboBox(this.availableParsers);
        converterLabel = new javax.swing.JLabel();
        fileLabel = new javax.swing.JLabel();
        fileTextField = new javax.swing.JTextField();
        openFileButton = new javax.swing.JButton();
        referenceNameLabel = new javax.swing.JLabel();
        referenceNameField = new javax.swing.JTextField();
        referenceLengthField = new javax.swing.JTextField();
        referenceLengthLabel = new javax.swing.JLabel();

        headerLabel.setText(org.openide.util.NbBundle.getMessage(ConverterSetupCard.class, "ConverterSetupCard.headerLabel.text")); // NOI18N

        converterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jok to BAM" }));
        converterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converterComboBoxActionPerformed(evt);
            }
        });

        converterLabel.setText(org.openide.util.NbBundle.getMessage(ConverterSetupCard.class, "ConverterSetupCard.converterLabel.text")); // NOI18N

        fileLabel.setText(org.openide.util.NbBundle.getMessage(ConverterSetupCard.class, "ConverterSetupCard.fileLabel.text")); // NOI18N

        fileTextField.setEditable(false);
        fileTextField.setText(org.openide.util.NbBundle.getMessage(ConverterSetupCard.class, "ConverterSetupCard.fileTextField.text")); // NOI18N

        openFileButton.setText(org.openide.util.NbBundle.getMessage(ConverterSetupCard.class, "ConverterSetupCard.openFileButton.text")); // NOI18N
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });

        referenceNameLabel.setText(org.openide.util.NbBundle.getMessage(ConverterSetupCard.class, "ConverterSetupCard.referenceNameLabel.text")); // NOI18N

        referenceNameField.setText(org.openide.util.NbBundle.getMessage(ConverterSetupCard.class, "ConverterSetupCard.referenceNameField.text")); // NOI18N
        referenceNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                referenceNameFieldKeyTyped(evt);
            }
        });

        referenceLengthField.setText(org.openide.util.NbBundle.getMessage(ConverterSetupCard.class, "ConverterSetupCard.referenceLengthField.text")); // NOI18N
        referenceLengthField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                referenceLengthFieldKeyTyped(evt);
            }
        });

        referenceLengthLabel.setText(org.openide.util.NbBundle.getMessage(ConverterSetupCard.class, "ConverterSetupCard.referenceLengthLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headerLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(converterLabel)
                            .addComponent(fileLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(referenceLengthLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(referenceNameLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(converterComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 285, Short.MAX_VALUE)
                            .addComponent(referenceNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(openFileButton))
                            .addComponent(referenceLengthField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(converterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(converterLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileLabel)
                    .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referenceNameLabel)
                    .addComponent(referenceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referenceLengthLabel)
                    .addComponent(referenceLengthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
        new VampFileChooser(VampFileChooser.OPEN_DIALOG, currentConverter.getFileExtensions(), currentConverter.getInputFileDescription()) {
            
            private static final long serialVersionUID = 1L;

            @Override
            public void save(String fileLocation) {
                throw new UnsupportedOperationException("Operation not supported!");
            }

            @Override
            public void open(String fileLocation) {
                fileTextField.setText(fileLocation);
                filePath = fileLocation;
                isRequiredInfoSet();
            }
        };
    }//GEN-LAST:event_openFileButtonActionPerformed

    private void converterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converterComboBoxActionPerformed
        this.selectConverter();
        this.isRequiredInfoSet();
    }//GEN-LAST:event_converterComboBoxActionPerformed

    private void referenceNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_referenceNameFieldKeyTyped
        char input = evt.getKeyChar();
        if (input != '\b') {
            this.referenceName = this.referenceNameField.getText() + evt.getKeyChar();
        } else {
            this.referenceName = this.referenceNameField.getText();
        }
        this.isRequiredInfoSet();
    }//GEN-LAST:event_referenceNameFieldKeyTyped

    private void referenceLengthFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_referenceLengthFieldKeyTyped
        String input = String.valueOf(evt.getKeyChar());
        String value = this.referenceLengthField.getText();
        String wholeInput = value.concat(input);
        if (input.equals("\b")) {
            if (GeneralUtils.isValidPositiveNumberInput(value)) {
                this.referenceLength = Integer.valueOf(value);
            } else {
                this.referenceLength = -1;
            }
        } else if (GeneralUtils.isValidPositiveNumberInput(wholeInput)) {
            this.referenceLength = Integer.valueOf(wholeInput);
        } else {
            JOptionPane.showMessageDialog(this, "Please enter a numerical reference length larger than 0!", "Invalid Length", JOptionPane.ERROR_MESSAGE);
            this.referenceLength = -1;
        }
        this.isRequiredInfoSet();

    }//GEN-LAST:event_referenceLengthFieldKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox converterComboBox;
    private javax.swing.JLabel converterLabel;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JTextField fileTextField;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JButton openFileButton;
    private javax.swing.JTextField referenceLengthField;
    private javax.swing.JLabel referenceLengthLabel;
    private javax.swing.JTextField referenceNameField;
    private javax.swing.JLabel referenceNameLabel;
    // End of variables declaration//GEN-END:variables
    /**
     * Selects the correct converter depending on the chosen one.
     */
    private void selectConverter() {
        Object selectedItem = this.converterComboBox.getSelectedItem();
        if (selectedItem instanceof ConverterI) {
             ConverterI newConverter = (ConverterI) selectedItem;
             if (this.currentConverter != newConverter) {
                 this.currentConverter = newConverter;
                 this.fileTextField.setText("");
             }
        }
    }

    public void isRequiredInfoSet() {
        if (filePath != null && currentConverter != null && referenceName != null && !referenceName.isEmpty() && referenceLength >= 0) {
            canConvert = true;
        } else {
            canConvert = false;
        }
        firePropertyChange(ConverterAction.PROP_CAN_CONVERT, null, canConvert);
    }

    public ConverterI getSelectedConverter() {
        return currentConverter;
    }

    public String getFilePath() {
        return filePath;
    }

    public int getReferenceLength() {
        return referenceLength;
    }

    public String getReferenceName() {
        return referenceName;
    }
    
    @Override
    public String getName() {
        return NbBundle.getMessage(ConverterSetupCard.class, "CTL_ConverterSetupCard.name");
    }

}
