package de.cebitec.readXplorer.view.tableVisualization;

import de.cebitec.readXplorer.view.dataVisualisation.BoundsInfoManager;

/**
 * This panel is a table panel for showing any kind of table. It shall be used
 * for creating any kind of table panels for various tables, which allow
 * updating the position of a reference viewer.
 * 
 * @author Rolf Hilker <rhilker at mikrobio.med.uni-giessen.de>
 */
public abstract class TablePanel extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;
    
    private BoundsInfoManager bim;

    /**
     * This panel is a table panel for showing any kind of table. It shall be
     * used for creating any kind of table panels for various tables, which
     * allow updating the position of a reference viewer.
     */
    public TablePanel() {
        initComponents();
    }
    
    /**
     * Set the bounds info manager needed for updating the currently shown
     * position. 
     * @param boundsInformationManager the bounds info manager belonging to this
     * analysis result
     */
    public void setBoundsInfoManager(BoundsInfoManager boundsInformationManager) {
        this.bim = boundsInformationManager;
    }
    
    /**
     * @return The bounds info manager needed for updating the currently shown
     * position. 
     */
    protected BoundsInfoManager getBoundsInfoManager() {
        return this.bim;
    }
    
    /**
     * @return The size of the data contained in this panel's table.
     */
    public abstract int getDataSize();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
