package de.cebitec.vamp.view.importer;

import java.util.Iterator;
import java.util.List;
import de.cebitec.vamp.importer.ReferenceJob;
import de.cebitec.vamp.importer.TrackJobs;

/**
 *
 * @author ddoppmeier
 */
public class ImportOverviewCard extends javax.swing.JPanel {

    private static final long serialVersionUID = 663057846;

    /** Creates new form ImportOverviewCard */
    public ImportOverviewCard() {
        initComponents();
    }

    void showOverview(List<ReferenceJob> refGenJobList, List<TrackJobs> trackJobList) {

        jTextArea1.setText("");

        if(!refGenJobList.isEmpty()){
            jTextArea1.append("References:\n");
            for(Iterator<ReferenceJob> it = refGenJobList.iterator(); it.hasNext(); ){
                ReferenceJob r = it.next();
                jTextArea1.append(r.getFile().getAbsolutePath()+"\n");
                jTextArea1.append("\t"+r.getName()+"\n");
                jTextArea1.append("\t"+r.getDescription()+"\n");
            }
            jTextArea1.append("\n");
        }


        if(!trackJobList.isEmpty()){
            jTextArea1.append("Tracks:\n");
            for(Iterator<TrackJobs> it = trackJobList.iterator(); it.hasNext(); ){
                TrackJobs r = it.next();
                jTextArea1.append(r.getFile().getAbsolutePath()+"\n");
                jTextArea1.append("\t"+r.getDescription()+"\n");
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
