package de.cebitec.vamp.differentialExpression.wizard;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;

public final class DeSeqVisualPanelFit extends JPanel {

    private DefaultListModel<String> allConditionGroupsModel = new DefaultListModel<>();
    private DefaultListModel<String> fittingOneModel = new DefaultListModel<>();
    private DefaultListModel<String> fittingTwoModel = new DefaultListModel<>();
    private List<String> fittingGroupOne = new ArrayList<>();
    private List<String> fittingGroupTwo = new ArrayList<>();

    /**
     * Creates new form DeSeqVisualPanelFit
     */
    public DeSeqVisualPanelFit() {
        initComponents();
    }

    public void updateConditionGroupsList(Set<String> conditionGroups) {
        boolean newDataSet = false;
        for (Iterator<String> it = conditionGroups.iterator(); it.hasNext();) {
            String currentGroup = it.next();
            if (!allConditionGroupsModel.contains(currentGroup) 
                    && !fittingOneModel.contains(currentGroup) 
                    && !fittingTwoModel.contains(currentGroup)) {
                newDataSet = true;
                break;
            }
        }
        if (newDataSet) {
            allConditionGroupsModel.clear();
            fittingOneModel.clear();
            fittingTwoModel.clear();
            for (Iterator<String> it = conditionGroups.iterator(); it.hasNext();) {
                String currentGroup = it.next();
                allConditionGroupsModel.addElement(currentGroup);
            }
        }
    }

    public List<String> getFittingGroupOne() {
        return fittingGroupOne;
    }

    public List<String> getFittingGroupTwo() {
        return fittingGroupTwo;
    }

    public boolean allConditionGroupsAssigned() {
        return allConditionGroupsModel.isEmpty();
    }

    @Override
    public String getName() {
        return "Fitting model";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        conditionGroupsList = new javax.swing.JList();
        addToFittingOne = new javax.swing.JButton();
        removeFromFittingOne = new javax.swing.JButton();
        addToFittingTwo = new javax.swing.JButton();
        removeFromFittingTwo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        fittingTwoList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        fittingOneList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        conditionGroupsList.setModel(allConditionGroupsModel);
        jScrollPane1.setViewportView(conditionGroupsList);

        org.openide.awt.Mnemonics.setLocalizedText(addToFittingOne, org.openide.util.NbBundle.getMessage(DeSeqVisualPanelFit.class, "DeSeqVisualPanelFit.addToFittingOne.text")); // NOI18N
        addToFittingOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToFittingOneActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(removeFromFittingOne, org.openide.util.NbBundle.getMessage(DeSeqVisualPanelFit.class, "DeSeqVisualPanelFit.removeFromFittingOne.text")); // NOI18N
        removeFromFittingOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFromFittingOneActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(addToFittingTwo, org.openide.util.NbBundle.getMessage(DeSeqVisualPanelFit.class, "DeSeqVisualPanelFit.addToFittingTwo.text")); // NOI18N
        addToFittingTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToFittingTwoActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(removeFromFittingTwo, org.openide.util.NbBundle.getMessage(DeSeqVisualPanelFit.class, "DeSeqVisualPanelFit.removeFromFittingTwo.text")); // NOI18N
        removeFromFittingTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFromFittingTwoActionPerformed(evt);
            }
        });

        fittingTwoList.setModel(fittingTwoModel);
        jScrollPane3.setViewportView(fittingTwoList);

        fittingOneList.setModel(fittingOneModel);
        jScrollPane2.setViewportView(fittingOneList);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(DeSeqVisualPanelFit.class, "DeSeqVisualPanelFit.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(DeSeqVisualPanelFit.class, "DeSeqVisualPanelFit.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(DeSeqVisualPanelFit.class, "DeSeqVisualPanelFit.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addToFittingTwo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addToFittingOne, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(removeFromFittingOne)
                            .addComponent(removeFromFittingTwo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel3))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(addToFittingOne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeFromFittingOne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addToFittingTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeFromFittingTwo)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addToFittingOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToFittingOneActionPerformed
        List<String> tracks = conditionGroupsList.getSelectedValuesList();
        for (Iterator<String> it = tracks.iterator(); it.hasNext();) {
            String currentGroup = it.next();
            allConditionGroupsModel.removeElement(currentGroup);
            fittingOneModel.addElement(currentGroup);
            fittingGroupOne.add(currentGroup);
        }
    }//GEN-LAST:event_addToFittingOneActionPerformed

    private void removeFromFittingOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFromFittingOneActionPerformed
        List<String> tracks = fittingOneList.getSelectedValuesList();
        for (Iterator<String> it = tracks.iterator(); it.hasNext();) {
            String currentGroup = it.next();
            fittingOneModel.removeElement(currentGroup);
            allConditionGroupsModel.addElement(currentGroup);
            fittingGroupOne.remove(currentGroup);
        }
    }//GEN-LAST:event_removeFromFittingOneActionPerformed

    private void addToFittingTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToFittingTwoActionPerformed
        List<String> tracks = conditionGroupsList.getSelectedValuesList();
        for (Iterator<String> it = tracks.iterator(); it.hasNext();) {
            String currentGroup = it.next();
            allConditionGroupsModel.removeElement(currentGroup);
            fittingTwoModel.addElement(currentGroup);
            fittingGroupTwo.add(currentGroup);
        }
    }//GEN-LAST:event_addToFittingTwoActionPerformed

    private void removeFromFittingTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFromFittingTwoActionPerformed
        List<String> tracks = fittingTwoList.getSelectedValuesList();
        for (Iterator<String> it = tracks.iterator(); it.hasNext();) {
            String currentGroup = it.next();
            fittingTwoModel.removeElement(currentGroup);
            allConditionGroupsModel.addElement(currentGroup);
            fittingGroupTwo.remove(currentGroup);
        }
    }//GEN-LAST:event_removeFromFittingTwoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToFittingOne;
    private javax.swing.JButton addToFittingTwo;
    private javax.swing.JList conditionGroupsList;
    private javax.swing.JList fittingOneList;
    private javax.swing.JList fittingTwoList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton removeFromFittingOne;
    private javax.swing.JButton removeFromFittingTwo;
    // End of variables declaration//GEN-END:variables
}
