package vamp.view.dataVisualisation;

import vamp.view.dataVisualisation.basePanel.BasePanelFactory;
import vamp.view.dataVisualisation.basePanel.BasePanel;
import vamp.view.dataVisualisation.trackViewer.TrackOptionsPanel;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import vamp.ApplicationController;
import vamp.databackend.dataObjects.PersistantTrack;
import vamp.view.dataVisualisation.histogramViewer.HistogramViewer;

/**
 *
 * @author ddoppmeier
 */
public class ExternalViewer extends javax.swing.JFrame {

    private static final long serialVersionUID = 24783163;
    private BasePanel alignmentBasePanel;
    private BasePanel logoBasePanel;
    private CardLayout cards;
    private TrackOptionsPanel parent;

    private static String LOGOCARD = "logo";
    private static String ALIGNMENTCARD = "alignment";

    /** Creates new form ExternalViewer */
    public ExternalViewer() {
        initComponents();
        Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "Do not use empty Constructor for this object! Standard constructor is only meant for GUI builder means");

    }

    public ExternalViewer(BasePanelFactory factory, PersistantTrack track, TrackOptionsPanel parent){
        this.parent = parent;
        initComponents();
        alignmentBasePanel = factory.getDetailTrackBasePanel(track);
        alignmentBasePanel.getViewer().setActive(false);
        logoBasePanel = factory.getSequenceLogoBasePanel(track);
        logoBasePanel.getViewer().setActive(true);

        cards = (CardLayout) cardPanel.getLayout();
        cardPanel.add(alignmentBasePanel, ALIGNMENTCARD);
        cardPanel.add(logoBasePanel, LOGOCARD);
        cards.show(cardPanel, LOGOCARD);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        switchPanel = new javax.swing.JPanel();
        seqlogoButton = new javax.swing.JButton();
        alignmentButton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        viewerPanel = new javax.swing.JPanel();
        cardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(ApplicationController.APPNAME+" Detailviewer");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        seqlogoButton.setText("Histogram");
        seqlogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seqlogoButtonActionPerformed(evt);
            }
        });

        alignmentButton.setText("Alignment");
        alignmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alignmentButtonActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Dialog", 1, 10));
        jCheckBox1.setText("Color Histogram");
        jCheckBox1.setMinimumSize(new java.awt.Dimension(50, 22));
        jCheckBox1.setPreferredSize(new java.awt.Dimension(100, 22));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout switchPanelLayout = new javax.swing.GroupLayout(switchPanel);
        switchPanel.setLayout(switchPanelLayout);
        switchPanelLayout.setHorizontalGroup(
            switchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(switchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(switchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seqlogoButton)
                    .addComponent(alignmentButton))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(switchPanelLayout.createSequentialGroup()
                .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        switchPanelLayout.setVerticalGroup(
            switchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(switchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seqlogoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alignmentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        getContentPane().add(switchPanel, java.awt.BorderLayout.WEST);

        viewerPanel.setPreferredSize(new java.awt.Dimension(490, 400));
        viewerPanel.setLayout(new java.awt.BorderLayout());

        cardPanel.setPreferredSize(new java.awt.Dimension(470, 400));
        cardPanel.setLayout(new java.awt.CardLayout());
        viewerPanel.add(cardPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(viewerPanel, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-572)/2, (screenSize.height-390)/2, 572, 390);
    }// </editor-fold>//GEN-END:initComponents

    private void seqlogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seqlogoButtonActionPerformed
        logoBasePanel.getViewer().setActive(true);
        alignmentBasePanel.getViewer().setActive(false);
        cards.show(cardPanel, LOGOCARD);
    }//GEN-LAST:event_seqlogoButtonActionPerformed

    private void alignmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alignmentButtonActionPerformed
        logoBasePanel.getViewer().setActive(false);
        alignmentBasePanel.getViewer().setActive(true);
        cards.show(cardPanel, ALIGNMENTCARD);
    }//GEN-LAST:event_alignmentButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.viewerClosed();
    }//GEN-LAST:event_formWindowClosing

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
     HistogramViewer vi = (HistogramViewer) logoBasePanel.getViewer();
     vi.isColored(jCheckBox1.isSelected());
     vi.boundsChangedHook();
     vi.repaint();
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alignmentButton;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JButton seqlogoButton;
    private javax.swing.JPanel switchPanel;
    private javax.swing.JPanel viewerPanel;
    // End of variables declaration//GEN-END:variables

    public void close() {
        alignmentBasePanel.close();
        alignmentBasePanel = null;
        logoBasePanel.close();
        logoBasePanel = null;
    }

}
