package de.cebitec.readXplorer.transcriptomeAnalyses.mainWizard;

import javax.swing.JPanel;

public final class AntisenseDetectionParamsVisualPanel extends JPanel {

    private final String wizardName;
    /**
     * Creates new form AntisenseDetectionParamsVisualPanel
     */
    public AntisenseDetectionParamsVisualPanel(String wizardName) {
        initComponents();
        this.wizardName = wizardName;
    }

    @Override
    public String getName() {
        return "Parameters for antisense-detection";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
