package de.cebitec.readXplorer.transcriptomeAnalyses.mainWizard;

import de.cebitec.readXplorer.databackend.connector.ProjectConnector;
import de.cebitec.readXplorer.databackend.connector.ReferenceConnector;
import java.awt.event.KeyEvent;
import java.util.prefs.Preferences;
import javax.swing.JPanel;
import org.openide.util.NbPreferences;

public final class TssDetectionParamsVisualPanel extends JPanel {

    private final String wizardName;
    private ReferenceConnector refGenConnector;
    private int nbOfFeatures;
    private int chromLength;

    /**
     * Creates new form TssDetectionParamsVisualPanel
     */
    public TssDetectionParamsVisualPanel(String wizardName, int referenceID) {
        initComponents();
        this.wizardName = wizardName;
        this.downstreamTextPane.setText("How many bases downstream the transcription start site would you like to have?");
        this.downstreamTextPane.setEditable(false);
        this.upstreamTextPane.setText("How many bases upstream the transcription start site would you like to have?");
        this.upstreamTextPane.setEditable(false);
        this.ratioTextPane.setText("Ration of the read starts on position i and i-1.");
        this.ratioTextPane.setEditable(false);
        this.updateFields();
        this.refGenConnector = ProjectConnector.getInstance().getRefGenomeConnector(referenceID);
        this.chromLength = refGenConnector.getRefGenome().getActiveChromLength();
        this.nbOfFeatures = refGenConnector.getFeaturesForClosedInterval(0, this.chromLength - 1, 
                refGenConnector.getRefGenome().getActiveChromId()).size();
    }

    @Override
    public String getName() {
        return "Parameters for TSS-detection";
    }

    public Double getFraction() {
        return Double.valueOf(fractionTextField.getText());
    }

    public Integer getRatio() {
        return Integer.valueOf(rationValueTextField.getText());
    }

    public Integer getUpstrteam() {
        return Integer.valueOf(upstreamRegionTextField.getText());
    }

    public Integer getDownstream() {
        return Integer.valueOf(downstreamRegionTextField.getText());
    }

    public boolean isExcludeInternalTSS() {
        return exclusionOfInternalTSSChcekbox.isSelected();
    }

    public int getExcludeTssDistance() {
        return Integer.valueOf(limitationOfDistanceToGeneTF.getText());
    }

    public int getKeepingInternalTssDistance() {
        return Integer.valueOf(keepInternalTssDistanceTF.getText());
    }

    /**
     * Updates the checkboxes for the read classes with the globally stored
     * settings for this wizard. If no settings were stored, the default
     * configuration is chosen.
     */
    private void updateFields() {
        Preferences pref = NbPreferences.forModule(Object.class);
        fractionTextField.setText(pref.get(wizardName + TranscriptomeAnalysisWizardIterator.PROP_Fraction, "0.05"));
        upstreamRegionTextField.setText(pref.get(wizardName + TranscriptomeAnalysisWizardIterator.PROP_UPSTREAM, "60"));
        downstreamRegionTextField.setText(pref.get(wizardName + TranscriptomeAnalysisWizardIterator.PROP_DOWNSTREAM, "2"));
        rationValueTextField.setText(pref.get(wizardName + TranscriptomeAnalysisWizardIterator.PROP_RATIO, "5"));
        limitationOfDistanceToGeneTF.setText(pref.get(wizardName + TranscriptomeAnalysisWizardIterator.PROP_EXCLUDE_TSS_DISTANCE, "500"));
        keepInternalTssDistanceTF.setText(pref.get(wizardName + TranscriptomeAnalysisWizardIterator.PROP_EXCLUDE_TSS_DISTANCE, "100"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fractionTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        upstreamRegionTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        downstreamRegionTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rationValueTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        upstreamTextPane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        downstreamTextPane = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        ratioTextPane = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        exclusionOfInternalTSSChcekbox = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        limitationOfDistanceToGeneTF = new javax.swing.JTextField();
        keepInternalTSSLabel = new javax.swing.JLabel();
        keepInternalTssDistanceTF = new javax.swing.JTextField();
        fractionDescriptionLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.jLabel1.text")); // NOI18N

        fractionTextField.setText(org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.fractionTextField.text")); // NOI18N
        fractionTextField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                fractionTextFieldMouseDragged(evt);
            }
        });
        fractionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fractionTextFieldActionPerformed(evt);
            }
        });
        fractionTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fractionTextFieldPropertyChange(evt);
            }
        });
        fractionTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fractionTextFieldKeyReleased(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.jLabel2.text_1")); // NOI18N

        upstreamRegionTextField.setText(org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.upstreamRegionTextField.text")); // NOI18N
        upstreamRegionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upstreamRegionTextFieldActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.jLabel3.text")); // NOI18N

        downstreamRegionTextField.setText(org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.downstreamRegionTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.jLabel4.text")); // NOI18N

        rationValueTextField.setText(org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.rationValueTextField.text")); // NOI18N
        rationValueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rationValueTextFieldActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(upstreamTextPane);

        jScrollPane3.setViewportView(downstreamTextPane);

        jScrollPane4.setViewportView(ratioTextPane);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(exclusionOfInternalTSSChcekbox, org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.exclusionOfInternalTSSChcekbox.text")); // NOI18N
        exclusionOfInternalTSSChcekbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exclusionOfInternalTSSChcekboxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.jLabel9.text")); // NOI18N

        limitationOfDistanceToGeneTF.setText(org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.limitationOfDistanceToGeneTF.text")); // NOI18N
        limitationOfDistanceToGeneTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitationOfDistanceToGeneTFActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(keepInternalTSSLabel, org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.keepInternalTSSLabel.text")); // NOI18N

        keepInternalTssDistanceTF.setText(org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.keepInternalTssDistanceTF.text")); // NOI18N

        fractionDescriptionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cebitec/readXplorer/transcriptomeAnalyses/resources/fractionDescription.PNG"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(fractionDescriptionLabel, org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.fractionDescriptionLabel.text_1")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(resultLabel, org.openide.util.NbBundle.getMessage(TssDetectionParamsVisualPanel.class, "TssDetectionParamsVisualPanel.resultLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fractionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(downstreamRegionTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(upstreamRegionTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(rationValueTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                                    .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(exclusionOfInternalTSSChcekbox, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(keepInternalTSSLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(keepInternalTssDistanceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(limitationOfDistanceToGeneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fractionDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(8, 8, 8))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fractionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fractionDescriptionLabel)
                    .addComponent(resultLabel))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(upstreamRegionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(downstreamRegionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(rationValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(limitationOfDistanceToGeneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keepInternalTSSLabel)
                    .addComponent(keepInternalTssDistanceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exclusionOfInternalTSSChcekbox))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void upstreamRegionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upstreamRegionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upstreamRegionTextFieldActionPerformed

    private void exclusionOfInternalTSSChcekboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exclusionOfInternalTSSChcekboxActionPerformed
        // TODO add your handling code here:
        if (keepInternalTSSLabel.isEnabled() && keepInternalTssDistanceTF.isEnabled()) {
            keepInternalTssDistanceTF.setEnabled(false);
            keepInternalTSSLabel.setEnabled(false);
        } else {
            keepInternalTssDistanceTF.setEnabled(true);
            keepInternalTSSLabel.setEnabled(true);
        }

    }//GEN-LAST:event_exclusionOfInternalTSSChcekboxActionPerformed

    private void limitationOfDistanceToGeneTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitationOfDistanceToGeneTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limitationOfDistanceToGeneTFActionPerformed

    private void rationValueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rationValueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rationValueTextFieldActionPerformed

    private void fractionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fractionTextFieldActionPerformed
    }//GEN-LAST:event_fractionTextFieldActionPerformed

    private void fractionTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fractionTextFieldPropertyChange
    }//GEN-LAST:event_fractionTextFieldPropertyChange

    private void fractionTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fractionTextFieldKeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Double.valueOf(fractionTextField.getText()) > 0.0) {
                double fraction = Double.parseDouble(fractionTextField.getText());
                double result = (this.chromLength / this.nbOfFeatures) * fraction;
                this.resultLabel.setText("" + result);
            }
        }
    }//GEN-LAST:event_fractionTextFieldKeyReleased

    private void fractionTextFieldMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fractionTextFieldMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_fractionTextFieldMouseDragged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField downstreamRegionTextField;
    private javax.swing.JTextPane downstreamTextPane;
    private javax.swing.JCheckBox exclusionOfInternalTSSChcekbox;
    private javax.swing.JLabel fractionDescriptionLabel;
    private javax.swing.JTextField fractionTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel keepInternalTSSLabel;
    private javax.swing.JTextField keepInternalTssDistanceTF;
    private javax.swing.JTextField limitationOfDistanceToGeneTF;
    private javax.swing.JTextPane ratioTextPane;
    private javax.swing.JTextField rationValueTextField;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField upstreamRegionTextField;
    private javax.swing.JTextPane upstreamTextPane;
    // End of variables declaration//GEN-END:variables
}
