/*
 * Copyright (C) 2014 Institute for Bioinformatics and Systems Biology, University Giessen, Germany
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package de.cebitec.readxplorer.ui.options;


import de.cebitec.readxplorer.api.constants.Colors;
import de.cebitec.readxplorer.utils.ColorUtils;
import de.cebitec.readxplorer.api.Classification;
import de.cebitec.readxplorer.api.enums.ComparisonClass;
import de.cebitec.readxplorer.api.enums.MappingClass;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import java.util.prefs.Preferences;
import javax.swing.JColorChooser;
import javax.swing.JPanel;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.util.NbPreferences;


/**
 * An option panel for changing the colors of the coverage and mapping classes
 * in ReadXplorer.
 * <p>
 * @author Rolf Hilker <rolf.hilker at mikrobio.med.uni-giessen.de>
 */
final class ColorsPanel extends OptionsPanel {

    private static final long serialVersionUID = 1L;
    private final ColorsOptionsPanelController controller;
    private final Preferences pref = NbPreferences.forModule( Object.class );
    private final Map<Classification, JPanel> classToPanelMap = new HashMap<>();


    /**
     * An option panel for changing the colors of the coverage and mapping
     * classes in ReadXplorer.
     * <p>
     * @param controller The controller belonging to this panel
     */
    ColorsPanel( ColorsOptionsPanelController controller ) {
        this.controller = controller;
        this.initComponents();
        this.initClassToPanelMap();
        // could do: listen to changes in form fields and call controller.changed()
    }


    private void initClassToPanelMap() {
        classToPanelMap.clear();
        classToPanelMap.put( MappingClass.PERFECT_MATCH, perfectColorPanel );
        classToPanelMap.put( MappingClass.BEST_MATCH, bestColorPanel );
        classToPanelMap.put( MappingClass.COMMON_MATCH, commonColorPanel );
        classToPanelMap.put( MappingClass.SINGLE_BEST_MATCH, singleBestColorPanel );
        classToPanelMap.put( MappingClass.SINGLE_PERFECT_MATCH, singlePerfectColorPanel );
        classToPanelMap.put( ComparisonClass.DIFF_COVERAGE, differenceColorPanel );
        classToPanelMap.put( ComparisonClass.TRACK1_COVERAGE, track1ColorPanel );
        classToPanelMap.put( ComparisonClass.TRACK2_COVERAGE, track2ColorPanel );
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uniformColorationCheckBox = new javax.swing.JCheckBox();
        bestMatchLabel = new javax.swing.JLabel();
        commonColorButton = new javax.swing.JButton();
        commonMatchLabel = new javax.swing.JLabel();
        perfectColorButton = new javax.swing.JButton();
        perfectMatchLabel = new javax.swing.JLabel();
        uniformColButton = new javax.swing.JButton();
        bestColorButton = new javax.swing.JButton();
        generalSeparator = new javax.swing.JSeparator();
        uniformColorLabel = new javax.swing.JLabel();
        singlePerfectMatchLabel = new javax.swing.JLabel();
        singleBestMatchLabel = new javax.swing.JLabel();
        perfectColorPanel = new javax.swing.JPanel();
        bestColorPanel = new javax.swing.JPanel();
        singlePerfectColorButton = new javax.swing.JButton();
        singlePerfectColorPanel = new javax.swing.JPanel();
        singleBestColorButton = new javax.swing.JButton();
        singleBestColorPanel = new javax.swing.JPanel();
        commonColorPanel = new javax.swing.JPanel();
        uniformColorPanel = new javax.swing.JPanel();
        resetButton = new javax.swing.JButton();
        doubleTrackSeparator = new javax.swing.JSeparator();
        differenceColorButton = new javax.swing.JButton();
        doubleTrackLabel = new javax.swing.JLabel();
        diffColorLabel = new javax.swing.JLabel();
        track1ColorLabel = new javax.swing.JLabel();
        track1ColorButton = new javax.swing.JButton();
        track2ColorLabel = new javax.swing.JLabel();
        track2ColorButton = new javax.swing.JButton();
        differenceColorPanel = new javax.swing.JPanel();
        track1ColorPanel = new javax.swing.JPanel();
        track2ColorPanel = new javax.swing.JPanel();
        backgroundColorButton = new javax.swing.JButton();
        backgroundColorPanel = new javax.swing.JPanel();
        backgroundColorLabel = new javax.swing.JLabel();
        generalSeparator1 = new javax.swing.JSeparator();

        org.openide.awt.Mnemonics.setLocalizedText(uniformColorationCheckBox, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.uniformColorationCheckBox.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(bestMatchLabel, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.bestMatchLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(commonColorButton, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.commonColorButton.text")); // NOI18N
        commonColorButton.setToolTipText(org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.commonColorButton.toolTipText")); // NOI18N
        commonColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonColorButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(commonMatchLabel, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.commonMatchLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(perfectColorButton, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.perfectColorButton.text")); // NOI18N
        perfectColorButton.setToolTipText(org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.perfectColorButton.toolTipText")); // NOI18N
        perfectColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfectColorButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(perfectMatchLabel, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.perfectMatchLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(uniformColButton, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.uniformColButton.text")); // NOI18N
        uniformColButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniformColButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(bestColorButton, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.bestColorButton.text")); // NOI18N
        bestColorButton.setToolTipText(org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.bestColorButton.toolTipText")); // NOI18N
        bestColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestColorButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(uniformColorLabel, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.uniformColorLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(singlePerfectMatchLabel, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.singlePerfectMatchLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(singleBestMatchLabel, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.singleBestMatchLabel.text")); // NOI18N

        perfectColorPanel.setBackground(new java.awt.Color(115, 226, 112));
        perfectColorPanel.setPreferredSize(new java.awt.Dimension(27, 27));

        javax.swing.GroupLayout perfectColorPanelLayout = new javax.swing.GroupLayout(perfectColorPanel);
        perfectColorPanel.setLayout(perfectColorPanelLayout);
        perfectColorPanelLayout.setHorizontalGroup(
            perfectColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        perfectColorPanelLayout.setVerticalGroup(
            perfectColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bestColorPanel.setBackground(new java.awt.Color(255, 250, 28));
        bestColorPanel.setPreferredSize(new java.awt.Dimension(27, 27));

        javax.swing.GroupLayout bestColorPanelLayout = new javax.swing.GroupLayout(bestColorPanel);
        bestColorPanel.setLayout(bestColorPanelLayout);
        bestColorPanelLayout.setHorizontalGroup(
            bestColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bestColorPanelLayout.setVerticalGroup(
            bestColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(singlePerfectColorButton, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.singlePerfectColorButton.text")); // NOI18N
        singlePerfectColorButton.setToolTipText(org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.singlePerfectColorButton.toolTipText")); // NOI18N
        singlePerfectColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singlePerfectColorButtonActionPerformed(evt);
            }
        });

        singlePerfectColorPanel.setBackground(new java.awt.Color(38, 180, 36));
        singlePerfectColorPanel.setPreferredSize(new java.awt.Dimension(27, 27));

        javax.swing.GroupLayout singlePerfectColorPanelLayout = new javax.swing.GroupLayout(singlePerfectColorPanel);
        singlePerfectColorPanel.setLayout(singlePerfectColorPanelLayout);
        singlePerfectColorPanelLayout.setHorizontalGroup(
            singlePerfectColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        singlePerfectColorPanelLayout.setVerticalGroup(
            singlePerfectColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(singleBestColorButton, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.singleBestColorButton.text")); // NOI18N
        singleBestColorButton.setToolTipText(org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.singleBestColorButton.toolTipText")); // NOI18N
        singleBestColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleBestColorButtonActionPerformed(evt);
            }
        });

        singleBestColorPanel.setBackground(new java.awt.Color(238, 216, 13));
        singleBestColorPanel.setPreferredSize(new java.awt.Dimension(27, 27));

        javax.swing.GroupLayout singleBestColorPanelLayout = new javax.swing.GroupLayout(singleBestColorPanel);
        singleBestColorPanel.setLayout(singleBestColorPanelLayout);
        singleBestColorPanelLayout.setHorizontalGroup(
            singleBestColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        singleBestColorPanelLayout.setVerticalGroup(
            singleBestColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        commonColorPanel.setBackground(new java.awt.Color(180, 41, 36));
        commonColorPanel.setPreferredSize(new java.awt.Dimension(27, 27));

        javax.swing.GroupLayout commonColorPanelLayout = new javax.swing.GroupLayout(commonColorPanel);
        commonColorPanel.setLayout(commonColorPanelLayout);
        commonColorPanelLayout.setHorizontalGroup(
            commonColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        commonColorPanelLayout.setVerticalGroup(
            commonColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        uniformColorPanel.setBackground(new java.awt.Color(51, 51, 255));
        uniformColorPanel.setPreferredSize(new java.awt.Dimension(27, 27));

        javax.swing.GroupLayout uniformColorPanelLayout = new javax.swing.GroupLayout(uniformColorPanel);
        uniformColorPanel.setLayout(uniformColorPanelLayout);
        uniformColorPanelLayout.setHorizontalGroup(
            uniformColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        uniformColorPanelLayout.setVerticalGroup(
            uniformColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(resetButton, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.resetButton.text")); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(differenceColorButton, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.differenceColorButton.text")); // NOI18N
        differenceColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                differenceColorButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(doubleTrackLabel, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.doubleTrackLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(diffColorLabel, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.diffColorLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(track1ColorLabel, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.track1ColorLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(track1ColorButton, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.track1ColorButton.text")); // NOI18N
        track1ColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                track1ColorButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(track2ColorLabel, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.track2ColorLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(track2ColorButton, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.track2ColorButton.text")); // NOI18N
        track2ColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                track2ColorButtonActionPerformed(evt);
            }
        });

        differenceColorPanel.setBackground(java.awt.Color.blue);
        differenceColorPanel.setPreferredSize(new java.awt.Dimension(27, 27));

        javax.swing.GroupLayout differenceColorPanelLayout = new javax.swing.GroupLayout(differenceColorPanel);
        differenceColorPanel.setLayout(differenceColorPanelLayout);
        differenceColorPanelLayout.setHorizontalGroup(
            differenceColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        differenceColorPanelLayout.setVerticalGroup(
            differenceColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        track1ColorPanel.setBackground(java.awt.Color.cyan);
        track1ColorPanel.setPreferredSize(new java.awt.Dimension(27, 27));

        javax.swing.GroupLayout track1ColorPanelLayout = new javax.swing.GroupLayout(track1ColorPanel);
        track1ColorPanel.setLayout(track1ColorPanelLayout);
        track1ColorPanelLayout.setHorizontalGroup(
            track1ColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        track1ColorPanelLayout.setVerticalGroup(
            track1ColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        track2ColorPanel.setBackground(new java.awt.Color(255, 117, 48));
        track2ColorPanel.setPreferredSize(new java.awt.Dimension(27, 27));

        javax.swing.GroupLayout track2ColorPanelLayout = new javax.swing.GroupLayout(track2ColorPanel);
        track2ColorPanel.setLayout(track2ColorPanelLayout);
        track2ColorPanelLayout.setHorizontalGroup(
            track2ColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        track2ColorPanelLayout.setVerticalGroup(
            track2ColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(backgroundColorButton, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.backgroundColorButton.text")); // NOI18N
        backgroundColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundColorButtonActionPerformed(evt);
            }
        });

        backgroundColorPanel.setBackground(Colors.BACKGROUND_COLOR );
        backgroundColorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        backgroundColorPanel.setPreferredSize(new java.awt.Dimension(27, 27));

        javax.swing.GroupLayout backgroundColorPanelLayout = new javax.swing.GroupLayout(backgroundColorPanel);
        backgroundColorPanel.setLayout(backgroundColorPanelLayout);
        backgroundColorPanelLayout.setHorizontalGroup(
            backgroundColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        backgroundColorPanelLayout.setVerticalGroup(
            backgroundColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(backgroundColorLabel, org.openide.util.NbBundle.getMessage(ColorsPanel.class, "ColorsPanel.backgroundColorLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(singleBestMatchLabel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(perfectMatchLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bestMatchLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(perfectColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addComponent(singleBestColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addComponent(bestColorPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(singlePerfectMatchLabel)
                                    .addComponent(commonMatchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(singlePerfectColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addComponent(commonColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bestColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(perfectColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(commonColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(10, 10, 10))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(singleBestColorButton)
                                    .addContainerGap()))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(singlePerfectColorButton)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generalSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doubleTrackSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(resetButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(diffColorLabel)
                                .addGap(48, 48, 48)
                                .addComponent(differenceColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(differenceColorButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(track1ColorLabel)
                                .addGap(63, 63, 63)
                                .addComponent(track1ColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(track1ColorButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uniformColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(doubleTrackLabel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uniformColorationCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uniformColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uniformColButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(track2ColorLabel)
                                    .addComponent(backgroundColorLabel))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(backgroundColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addComponent(track2ColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(track2ColorButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(backgroundColorButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(generalSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(perfectMatchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bestMatchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(perfectColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(perfectColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bestColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bestColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commonMatchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commonColorButton)
                    .addComponent(commonColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(singlePerfectColorButton)
                            .addComponent(singlePerfectColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(singlePerfectMatchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(singleBestColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(singleBestColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(singleBestMatchLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uniformColorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uniformColButton)
                    .addComponent(uniformColorationCheckBox)
                    .addComponent(uniformColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doubleTrackSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doubleTrackLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(diffColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(differenceColorButton))
                                    .addComponent(differenceColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(track1ColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(track1ColorButton)))
                            .addComponent(track1ColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(track2ColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(track2ColorButton)))
                    .addComponent(track2ColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(generalSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backgroundColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundColorButton))
                .addGap(18, 18, 18)
                .addComponent(resetButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void perfectColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfectColorButtonActionPerformed
        this.displayColorChooser( perfectColorPanel );
}//GEN-LAST:event_perfectColorButtonActionPerformed

    private void uniformColButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniformColButtonActionPerformed
        this.displayColorChooser( uniformColorPanel );
}//GEN-LAST:event_uniformColButtonActionPerformed

    private void bestColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestColorButtonActionPerformed
        this.displayColorChooser( bestColorPanel );
}//GEN-LAST:event_bestColorButtonActionPerformed

    private void singlePerfectColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singlePerfectColorButtonActionPerformed
        this.displayColorChooser( singlePerfectColorPanel );
    }//GEN-LAST:event_singlePerfectColorButtonActionPerformed

    private void singleBestColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleBestColorButtonActionPerformed
        this.displayColorChooser( singleBestColorPanel );
    }//GEN-LAST:event_singleBestColorButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        perfectColorPanel.setBackground(Colors.PERFECT_MATCH );
        bestColorPanel.setBackground(Colors.BEST_MATCH );
        commonColorPanel.setBackground(Colors.COMMON_MATCH );
        singlePerfectColorPanel.setBackground(Colors.PERFECT_MATCH_SINGLE );
        singleBestColorPanel.setBackground(Colors.BEST_MATCH_SINGLE );
        uniformColorPanel.setBackground( Color.BLUE );
        differenceColorPanel.setBackground(Colors.COV_DIFF_COLOR );
        track1ColorPanel.setBackground(Colors.TRACK1_COLOR );
        track2ColorPanel.setBackground(Colors.TRACK2_COLOR );
        backgroundColorPanel.setBackground(Colors.BACKGROUND_COLOR );
    }//GEN-LAST:event_resetButtonActionPerformed

    private void differenceColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_differenceColorButtonActionPerformed
        this.displayColorChooser( differenceColorPanel );
    }//GEN-LAST:event_differenceColorButtonActionPerformed

    private void track1ColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_track1ColorButtonActionPerformed
        this.displayColorChooser( track1ColorPanel );
    }//GEN-LAST:event_track1ColorButtonActionPerformed

    private void track2ColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_track2ColorButtonActionPerformed
        this.displayColorChooser( track2ColorPanel );
    }//GEN-LAST:event_track2ColorButtonActionPerformed

    private void commonColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commonColorButtonActionPerformed
        this.displayColorChooser( commonColorPanel );
    }//GEN-LAST:event_commonColorButtonActionPerformed

    private void backgroundColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundColorButtonActionPerformed
        this.displayColorChooser( backgroundColorPanel );
    }//GEN-LAST:event_backgroundColorButtonActionPerformed


    @Override
    void load() {
        // read settings and initialize GUI
        Map<Classification, Color> classToColorMap = ColorUtils.updateClassificationColors();
        for( Classification classType : classToPanelMap.keySet() ) {
            classToPanelMap.get( classType ).setBackground( classToColorMap.get( classType ) );
        }

        updatePanelColor(Colors.UNIFORM_COLOR_STRING, Color.BLUE, uniformColorPanel );
        updatePanelColor(Colors.BACKGROUND_COLOR_STRING, Colors.BACKGROUND_COLOR, backgroundColorPanel );

        uniformColorationCheckBox.setSelected(this.pref.getBoolean(Colors.UNIFORM_DESIRED, false ) );
    }


    /**
     * Update the color panels according to the colors chosen by the user during
     * the last session.
     * <p>
     * @param colorString  RGB string of the color to display on the panel
     * @param defaultColor the default color for a classification
     * @param colorPanel   the panel for displaying the color
     */
    private void updatePanelColor( String colorString, Color defaultColor, JPanel colorPanel ) {
        String colorRGB = this.pref.get( colorString, "" );
        if( colorRGB.isEmpty() ) {
            colorPanel.setBackground( defaultColor );
        } else {
            colorPanel.setBackground( new Color( Integer.parseInt( colorRGB ) ) );
        }
    }


    @Override
    void store() {
        // store modified settings
        this.pref.putBoolean(Colors.UNIFORM_DESIRED, uniformColorationCheckBox.isSelected() );
        this.pref.put(Colors.UNIFORM_COLOR_STRING, Integer.toString( uniformColorPanel.getBackground().getRGB() ) );
        this.pref.put(Colors.BACKGROUND_COLOR_STRING, Integer.toString( backgroundColorPanel.getBackground().getRGB() ) );

        for( Classification classType : classToPanelMap.keySet() ) {
            this.storeColor( classType );
        }
    }


    /**
     * Retrieves the color of a given classification from the classToPanel list
     * and stores it in the classification color field and in the preferences.
     * <p>
     * @param classType The class type whose color to store
     */
    private void storeColor( Classification classType ) {
        String colorRGB = Integer.toString( classToPanelMap.get( classType ).getBackground().getRGB() );
        this.pref.put( classType.getString(), colorRGB );
    }


    /**
     * Displays a color chooser for the selected button and updates the
     * corresponding panel when a new color was chosen.
     * <p>
     * @param panel the color panel to update
     */
    private void displayColorChooser( JPanel panel ) {
        JColorChooser colChooser = new JColorChooser();
        DialogDescriptor d = new DialogDescriptor( colChooser, "Choose a color" );
        DialogDisplayer.getDefault().createDialog( d ).setVisible( true );
        if( d.getValue().equals( DialogDescriptor.OK_OPTION ) ) {
            panel.setBackground( colChooser.getColor() );
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backgroundColorButton;
    private javax.swing.JLabel backgroundColorLabel;
    private javax.swing.JPanel backgroundColorPanel;
    private javax.swing.JButton bestColorButton;
    private javax.swing.JPanel bestColorPanel;
    private javax.swing.JLabel bestMatchLabel;
    private javax.swing.JButton commonColorButton;
    private javax.swing.JPanel commonColorPanel;
    private javax.swing.JLabel commonMatchLabel;
    private javax.swing.JLabel diffColorLabel;
    private javax.swing.JButton differenceColorButton;
    private javax.swing.JPanel differenceColorPanel;
    private javax.swing.JLabel doubleTrackLabel;
    private javax.swing.JSeparator doubleTrackSeparator;
    private javax.swing.JSeparator generalSeparator;
    private javax.swing.JSeparator generalSeparator1;
    private javax.swing.JButton perfectColorButton;
    private javax.swing.JPanel perfectColorPanel;
    private javax.swing.JLabel perfectMatchLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton singleBestColorButton;
    private javax.swing.JPanel singleBestColorPanel;
    private javax.swing.JLabel singleBestMatchLabel;
    private javax.swing.JButton singlePerfectColorButton;
    private javax.swing.JPanel singlePerfectColorPanel;
    private javax.swing.JLabel singlePerfectMatchLabel;
    private javax.swing.JButton track1ColorButton;
    private javax.swing.JLabel track1ColorLabel;
    private javax.swing.JPanel track1ColorPanel;
    private javax.swing.JButton track2ColorButton;
    private javax.swing.JLabel track2ColorLabel;
    private javax.swing.JPanel track2ColorPanel;
    private javax.swing.JButton uniformColButton;
    private javax.swing.JLabel uniformColorLabel;
    private javax.swing.JPanel uniformColorPanel;
    private javax.swing.JCheckBox uniformColorationCheckBox;
    // End of variables declaration//GEN-END:variables

}
