/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cebitec.vamp.tools.snp454;

import de.cebitec.vamp.databackend.dataObjects.Snp454;
import de.cebitec.vamp.util.TabWithCloseX;
import de.cebitec.vamp.view.TopComponentExtended;
import de.cebitec.vamp.view.dataVisualisation.trackViewer.TrackViewer;
import java.awt.CardLayout;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JPanel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//de.cebitec.vamp.tools.snp454//SNP_Detection454//EN",
autostore = false)
@TopComponent.Description(preferredID = "SNP_Detection454TopComponent",
iconBase = "de/cebitec/vamp/tools/snp454/snpDetection.png",
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "output", openAtStartup = false)
@ActionID(category = "Window", id = "de.cebitec.vamp.tools.snp454.SNP_Detection454TopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_SNP_Detection454Action",
preferredID = "SNP_Detection454TopComponent")
public final class SNP_Detection454TopComponent extends TopComponentExtended {
    
    private static final long serialVersionUID = 1L;
    private static SNP_Detection454TopComponent instance;
    
    private static final String PREFERRED_ID = "SNP_DetectionTopComponent";

    public SNP_Detection454TopComponent() {
        initComponents();
        setName(NbBundle.getMessage(SNP_Detection454TopComponent.class, "CTL_SNP_Detection454TopComponent"));
        setToolTipText(NbBundle.getMessage(SNP_Detection454TopComponent.class, "HINT_SNP_Detection454TopComponent"));
        
        // add listener to close TopComponent when no tabs are shown
        snpTabs.addContainerListener(new ContainerListener() {

            @Override
            public void componentAdded(ContainerEvent e) {

            }

            @Override
            public void componentRemoved(ContainerEvent e) {
                if (snpTabs.getTabCount() == 0){
                    WindowManager.getDefault().findTopComponent(PREFERRED_ID).close();
                }
            }
        });
    }
    
    /**
     * Creates a complete snp detection panel, that is used in the JTabbedPane.
     * The <code>TrackViewer</code> instance is used to set up the setup and
     * result panels.
     *
     * @param trackViewer instance used for this panels panels.
     * @return complete snp detection panel
     */
    private javax.swing.JPanel getSnpDetectionPanel(TrackViewer trackViewer){
        // initialise components
        final JPanel snpDetectionPanel = new JPanel();
        SNP_Detection454SetupPanel setupPanel = new SNP_Detection454SetupPanel();
        final SNP_Detection454ResultPanel resultPanel = new SNP_Detection454ResultPanel();

        // assign the trackviewer
        setupPanel.setCon(trackViewer.getTrackCon());
        resultPanel.setBoundsInfoManager(trackViewer.getBoundsInformationManager());

        // listen on changes of the search
        setupPanel.addPropertyChangeListener(SNP_Detection454SetupPanel.PROP_SNPS_LOADED, new PropertyChangeListener() {

            @Override
            @SuppressWarnings("unchecked")
            public void propertyChange(PropertyChangeEvent evt) {
                resultPanel.addSNPs((List<Snp454>) evt.getNewValue());
                ((CardLayout) snpDetectionPanel.getLayout()).show(snpDetectionPanel, "results");
            }
        });

        // setup the layout
        snpDetectionPanel.setLayout(new java.awt.CardLayout());
        snpDetectionPanel.add(setupPanel, "setup");
        snpDetectionPanel.add(resultPanel, "results");

        return snpDetectionPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        snpDetection454PanelTemplate = new javax.swing.JPanel();
        snpTabs = new javax.swing.JTabbedPane();

        snpDetection454SetupPanelTemplate = new SNP_Detection454SetupPanel();
        snpDetection454ResultPanelTemplate = new SNP_Detection454ResultPanel();
        snpDetection454PanelTemplate.setLayout(new java.awt.CardLayout());
        snpDetection454PanelTemplate.add(snpDetection454SetupPanelTemplate, "setup");
        snpDetection454PanelTemplate.add(snpDetection454ResultPanelTemplate, "results");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(snpTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(snpTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel snpDetection454PanelTemplate;
    private de.cebitec.vamp.tools.snp454.SNP_Detection454SetupPanel snpDetection454SetupPanelTemplate;
    private de.cebitec.vamp.tools.snp454.SNP_Detection454ResultPanel snpDetection454ResultPanelTemplate;
    private javax.swing.JTabbedPane snpTabs;
    // End of variables declaration//GEN-END:variables
   /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized SNP_Detection454TopComponent getDefault() {
        if (instance == null) {
            instance = new SNP_Detection454TopComponent();
        }
        return instance;
    }

    /**
     * Obtain the SNP_Detection454TopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized SNP_Detection454TopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(SNP_Detection454TopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof SNP_Detection454TopComponent) {
            return (SNP_Detection454TopComponent) win;
        }
        Logger.getLogger(SNP_Detection454TopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID
                + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {

    }

    @Override
    public void componentClosed() {
        snpTabs.removeAll();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // store your settings
    }

    Object readProperties(java.util.Properties p) {
        if (instance == null) {
            instance = this;
        }
        instance.readPropertiesImpl(p);
        return instance;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    public void openDetectionTab(TrackViewer trackViewer){
        snpTabs.addTab(trackViewer.getTrackCon().getAssociatedTrackName(), getSnpDetectionPanel(trackViewer));
        snpTabs.setTabComponentAt(snpTabs.getTabCount()-1, new TabWithCloseX(snpTabs));
    }
}
